// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/points-svc/internal/dao/internal"
)

// pointsGrantDetailDao is the data access object for the table points_grant_detail.
// You can define custom methods on it to extend its functionality as needed.
type pointsGrantDetailDao struct {
	*internal.PointsGrantDetailDao
}

var (
	// PointsGrantDetail is a globally accessible object for table points_grant_detail operations.
	PointsGrantDetail = pointsGrantDetailDao{internal.NewPointsGrantDetailDao()}
)

// Add your custom methods and functionality below.
