// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/points-svc/internal/dao/internal"
)

// pointsLedgerDao is the data access object for the table points_ledger.
// You can define custom methods on it to extend its functionality as needed.
type pointsLedgerDao struct {
	*internal.PointsLedgerDao
}

var (
	// PointsLedger is a globally accessible object for table points_ledger operations.
	PointsLedger = pointsLedgerDao{internal.NewPointsLedgerDao()}
)

// Add your custom methods and functionality below.
