// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/points-svc/internal/dao/internal"
)

// pointsOutboxEventDao is the data access object for the table points_outbox_event.
// You can define custom methods on it to extend its functionality as needed.
type pointsOutboxEventDao struct {
	*internal.PointsOutboxEventDao
}

var (
	// PointsOutboxEvent is a globally accessible object for table points_outbox_event operations.
	PointsOutboxEvent = pointsOutboxEventDao{internal.NewPointsOutboxEventDao()}
)

// Add your custom methods and functionality below.
