// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/points-svc/internal/dao/internal"
)

// pointsExpireBucketDao is the data access object for the table points_expire_bucket.
// You can define custom methods on it to extend its functionality as needed.
type pointsExpireBucketDao struct {
	*internal.PointsExpireBucketDao
}

var (
	// PointsExpireBucket is a globally accessible object for table points_expire_bucket operations.
	PointsExpireBucket = pointsExpireBucketDao{internal.NewPointsExpireBucketDao()}
)

// Add your custom methods and functionality below.
