// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/points-svc/internal/dao/internal"
)

// pointsRuleConfigDao is the data access object for the table points_rule_config.
// You can define custom methods on it to extend its functionality as needed.
type pointsRuleConfigDao struct {
	*internal.PointsRuleConfigDao
}

var (
	// PointsRuleConfig is a globally accessible object for table points_rule_config operations.
	PointsRuleConfig = pointsRuleConfigDao{internal.NewPointsRuleConfigDao()}
)

// Add your custom methods and functionality below.
