// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/points-svc/internal/dao/internal"
)

// pointsAccountDao is the data access object for the table points_account.
// You can define custom methods on it to extend its functionality as needed.
type pointsAccountDao struct {
	*internal.PointsAccountDao
}

var (
	// PointsAccount is a globally accessible object for table points_account operations.
	PointsAccount = pointsAccountDao{internal.NewPointsAccountDao()}
)

// Add your custom methods and functionality below.
