// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/points-svc/internal/dao/internal"
)

// pointsRefundActionDao is the data access object for the table points_refund_action.
type pointsRefundActionDao struct {
	*internal.PointsRefundActionDao
}

var (
	// PointsRefundAction is a globally accessible object for table points_refund_action operations.
	PointsRefundAction = pointsRefundActionDao{internal.NewPointsRefundActionDao()}
)
