// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/points-svc/internal/dao/internal"
)

// pointsReservationDao is the data access object for the table points_reservation.
// You can define custom methods on it to extend its functionality as needed.
type pointsReservationDao struct {
	*internal.PointsReservationDao
}

var (
	// PointsReservation is a globally accessible object for table points_reservation operations.
	PointsReservation = pointsReservationDao{internal.NewPointsReservationDao()}
)

// Add your custom methods and functionality below.
