// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/points-svc/internal/dao/internal"
)

// pointsConsumptionDetailDao is the data access object for the table points_consumption_detail.
// You can define custom methods on it to extend its functionality as needed.
type pointsConsumptionDetailDao struct {
	*internal.PointsConsumptionDetailDao
}

var (
	// PointsConsumptionDetail is a globally accessible object for table points_consumption_detail operations.
	PointsConsumptionDetail = pointsConsumptionDetailDao{internal.NewPointsConsumptionDetailDao()}
)

// Add your custom methods and functionality below.
