// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/agent-svc/internal/dao/internal"
)

// agentEscalationTicketDao is the data access object for the table agent_escalation_ticket.
// You can define custom methods on it to extend its functionality as needed.
type agentEscalationTicketDao struct {
	*internal.AgentEscalationTicketDao
}

var (
	// AgentEscalationTicket is a globally accessible object for table agent_escalation_ticket operations.
	AgentEscalationTicket = agentEscalationTicketDao{internal.NewAgentEscalationTicketDao()}
)

// Add your custom methods and functionality below.
