// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/agent-svc/internal/dao/internal"
)

// agentFeedbackDao is the data access object for the table agent_feedback.
// You can define custom methods on it to extend its functionality as needed.
type agentFeedbackDao struct {
	*internal.AgentFeedbackDao
}

var (
	// AgentFeedback is a globally accessible object for table agent_feedback operations.
	AgentFeedback = agentFeedbackDao{internal.NewAgentFeedbackDao()}
)

// Add your custom methods and functionality below.
