// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/agent-svc/internal/dao/internal"
)

// agentRunDao is the data access object for the table agent_run.
// You can define custom methods on it to extend its functionality as needed.
type agentRunDao struct {
	*internal.AgentRunDao
}

var (
	// AgentRun is a globally accessible object for table agent_run operations.
	AgentRun = agentRunDao{internal.NewAgentRunDao()}
)

// Add your custom methods and functionality below.
