// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/agent-svc/internal/dao/internal"
)

// agentToolCallLogDao is the data access object for the table agent_tool_call_log.
// You can define custom methods on it to extend its functionality as needed.
type agentToolCallLogDao struct {
	*internal.AgentToolCallLogDao
}

var (
	// AgentToolCallLog is a globally accessible object for table agent_tool_call_log operations.
	AgentToolCallLog = agentToolCallLogDao{internal.NewAgentToolCallLogDao()}
)

// Add your custom methods and functionality below.
