// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/agent-svc/internal/dao/internal"
)

// agentKnowledgeChunkDao is the data access object for the table agent_knowledge_chunk.
// You can define custom methods on it to extend its functionality as needed.
type agentKnowledgeChunkDao struct {
	*internal.AgentKnowledgeChunkDao
}

var (
	// AgentKnowledgeChunk is a globally accessible object for table agent_knowledge_chunk operations.
	AgentKnowledgeChunk = agentKnowledgeChunkDao{internal.NewAgentKnowledgeChunkDao()}
)

// Add your custom methods and functionality below.
