// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/agent-svc/internal/dao/internal"
)

// agentConversationDao is the data access object for the table agent_conversation.
// You can define custom methods on it to extend its functionality as needed.
type agentConversationDao struct {
	*internal.AgentConversationDao
}

var (
	// AgentConversation is a globally accessible object for table agent_conversation operations.
	AgentConversation = agentConversationDao{internal.NewAgentConversationDao()}
)

// Add your custom methods and functionality below.
