// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/agent-svc/internal/dao/internal"
)

// agentKnowledgeDocDao is the data access object for the table agent_knowledge_doc.
// You can define custom methods on it to extend its functionality as needed.
type agentKnowledgeDocDao struct {
	*internal.AgentKnowledgeDocDao
}

var (
	// AgentKnowledgeDoc is a globally accessible object for table agent_knowledge_doc operations.
	AgentKnowledgeDoc = agentKnowledgeDocDao{internal.NewAgentKnowledgeDocDao()}
)

// Add your custom methods and functionality below.
