// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/agent-svc/internal/dao/internal"
)

// agentIdempotencyDao is the data access object for the table agent_idempotency.
// You can define custom methods on it to extend its functionality as needed.
type agentIdempotencyDao struct {
	*internal.AgentIdempotencyDao
}

var (
	// AgentIdempotency is a globally accessible object for table agent_idempotency operations.
	AgentIdempotency = agentIdempotencyDao{internal.NewAgentIdempotencyDao()}
)

// Add your custom methods and functionality below.
