// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/agent-svc/internal/dao/internal"
)

// agentMessageDao is the data access object for the table agent_message.
// You can define custom methods on it to extend its functionality as needed.
type agentMessageDao struct {
	*internal.AgentMessageDao
}

var (
	// AgentMessage is a globally accessible object for table agent_message operations.
	AgentMessage = agentMessageDao{internal.NewAgentMessageDao()}
)

// Add your custom methods and functionality below.
