CREATE TABLE IF NOT EXISTS notification_template (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  template_code VARCHAR(64) NOT NULL,
  channel TINYINT UNSIGNED NOT NULL DEFAULT 0,
  biz_type TINYINT UNSIGNED NOT NULL DEFAULT 0,
  title_tpl VARCHAR(255) NOT NULL DEFAULT '',
  content_tpl MEDIUMTEXT,
  enabled TINYINT UNSIGNED NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_template_code_channel (template_code, channel)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS notification_task (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  notification_no VARCHAR(64) NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  target_address VARCHAR(128) NOT NULL DEFAULT '',
  template_code VARCHAR(64) NOT NULL,
  channel TINYINT UNSIGNED NOT NULL DEFAULT 0,
  biz_type TINYINT UNSIGNED NOT NULL DEFAULT 0,
  dedupe_key VARCHAR(128) NOT NULL DEFAULT '',
  status TINYINT UNSIGNED NOT NULL DEFAULT 1,
  blocked_by_preference TINYINT UNSIGNED NOT NULL DEFAULT 0,
  blocked_by_frequency TINYINT UNSIGNED NOT NULL DEFAULT 0,
  params_json MEDIUMTEXT,
  provider_message_id VARCHAR(128) NOT NULL DEFAULT '',
  error_code VARCHAR(64) NOT NULL DEFAULT '',
  error_message VARCHAR(255) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_notification_no (notification_no),
  UNIQUE KEY uniq_channel_dedupe (channel, dedupe_key),
  KEY idx_user_created (user_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS notification_channel_record (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  notification_no VARCHAR(64) NOT NULL,
  channel TINYINT UNSIGNED NOT NULL DEFAULT 0,
  provider_code VARCHAR(64) NOT NULL DEFAULT 'MOCK',
  provider_message_id VARCHAR(128) NOT NULL DEFAULT '',
  provider_response MEDIUMTEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_notification_no (notification_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS notification_dead_letter (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  notification_no VARCHAR(64) NOT NULL,
  reason_code VARCHAR(64) NOT NULL,
  payload_json MEDIUMTEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_notification_no (notification_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS user_notification_preference (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  allow_transactional_sms TINYINT UNSIGNED NOT NULL DEFAULT 1,
  allow_marketing_sms TINYINT UNSIGNED NOT NULL DEFAULT 0,
  allow_transactional_email TINYINT UNSIGNED NOT NULL DEFAULT 1,
  allow_marketing_email TINYINT UNSIGNED NOT NULL DEFAULT 0,
  allow_push TINYINT UNSIGNED NOT NULL DEFAULT 1,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS notification_frequency_guard (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  guard_key VARCHAR(191) NOT NULL,
  minute_bucket VARCHAR(16) NOT NULL,
  day_bucket VARCHAR(10) NOT NULL,
  minute_count INT UNSIGNED NOT NULL DEFAULT 0,
  day_count INT UNSIGNED NOT NULL DEFAULT 0,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_guard_bucket (guard_key, minute_bucket, day_bucket)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS notification_outbox_event (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  event_no VARCHAR(64) NOT NULL,
  event_type VARCHAR(64) NOT NULL,
  payload_json MEDIUMTEXT,
  status TINYINT UNSIGNED NOT NULL DEFAULT 0,
  retry_count INT UNSIGNED NOT NULL DEFAULT 0,
  next_retry_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_event_no (event_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;