CREATE DATABASE IF NOT EXISTS shopa_notification_svc CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE shopa_notification_svc;

CREATE TABLE IF NOT EXISTS notification_template (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  template_code VARCHAR(64) NOT NULL,
  channel TINYINT UNSIGNED NOT NULL DEFAULT 0,
  biz_type TINYINT UNSIGNED NOT NULL DEFAULT 0,
  title VARCHAR(128) NOT NULL DEFAULT '',
  body_template TEXT,
  enabled TINYINT UNSIGNED NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_template_code_channel(template_code, channel)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS notification_task (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  notification_no VARCHAR(64) NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  target_address VARCHAR(128) NOT NULL DEFAULT '',
  template_code VARCHAR(64) NOT NULL,
  channel TINYINT UNSIGNED NOT NULL DEFAULT 0,
  biz_type TINYINT UNSIGNED NOT NULL DEFAULT 0,
  status TINYINT UNSIGNED NOT NULL DEFAULT 1,
  blocked_by_preference TINYINT UNSIGNED NOT NULL DEFAULT 0,
  blocked_by_frequency TINYINT UNSIGNED NOT NULL DEFAULT 0,
  params_json MEDIUMTEXT,
  dedupe_key VARCHAR(128) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_notification_no(notification_no),
  KEY idx_user_created(user_id, created_at),
  KEY idx_template_channel(template_code, channel)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS notification_channel_record (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  notification_no VARCHAR(64) NOT NULL,
  provider_message_id VARCHAR(128) NOT NULL DEFAULT '',
  status TINYINT UNSIGNED NOT NULL DEFAULT 1,
  error_code VARCHAR(64) NOT NULL DEFAULT '',
  error_message VARCHAR(255) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_notification_provider(notification_no, provider_message_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS notification_dead_letter (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  notification_no VARCHAR(64) NOT NULL,
  reason_code VARCHAR(64) NOT NULL,
  reason_message VARCHAR(255) NOT NULL DEFAULT '',
  payload_json MEDIUMTEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_notification_dead(notification_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS user_notification_preference (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  allow_transactional_sms TINYINT UNSIGNED NOT NULL DEFAULT 1,
  allow_marketing_sms TINYINT UNSIGNED NOT NULL DEFAULT 0,
  allow_transactional_email TINYINT UNSIGNED NOT NULL DEFAULT 1,
  allow_marketing_email TINYINT UNSIGNED NOT NULL DEFAULT 0,
  allow_push TINYINT UNSIGNED NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_user_id(user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS notification_frequency_guard (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  guard_key VARCHAR(191) NOT NULL,
  day_key VARCHAR(16) NOT NULL,
  minute_count INT UNSIGNED NOT NULL DEFAULT 0,
  day_count INT UNSIGNED NOT NULL DEFAULT 0,
  expires_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_guard_day(guard_key, day_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS notification_outbox_event (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  event_id VARCHAR(64) NOT NULL,
  aggregate_type VARCHAR(64) NOT NULL,
  aggregate_id VARCHAR(64) NOT NULL,
  event_type VARCHAR(128) NOT NULL,
  payload_json MEDIUMTEXT,
  status TINYINT UNSIGNED NOT NULL DEFAULT 0,
  retry_count INT UNSIGNED NOT NULL DEFAULT 0,
  next_retry_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_event_id(event_id),
  KEY idx_status_next_retry(status, next_retry_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
