-- ============================================================================
-- iam-svc: bootstrap admin accounts and grants (idempotent)
-- ============================================================================
USE `shopa_iam_svc`;
SET NAMES utf8mb4;

-- 1) Configure bootstrap admin account.
--    You can change phone/email/default password before running this script.
--    Default password plaintext: Admin@123456
SET @admin_phone := '13364027679';
SET @admin_email := 'admin@shopa.local';
SET @admin_user_id_fallback := 900000000000000001;

-- Argon2id hash/salt for "Admin@123456" generated by iam-svc password policy.
SET @password_hash := 'jfYpIFN4F5i2ttw0GUCLN3GXB4BjrWphJ9nq1qfKZW0';
SET @password_salt := 'bAzR/cOL9cFwqW7szKCU+Q';

-- 2) If the phone already exists, reuse that user; otherwise create one.
SET @admin_user_id := (
  SELECT `user_id`
  FROM `iam_user_auth`
  WHERE `phone` = @admin_phone
  LIMIT 1
);
SET @admin_user_id := IFNULL(@admin_user_id, @admin_user_id_fallback);

INSERT INTO `iam_user_auth` (
  `user_id`, `phone`, `email`, `password_hash`, `password_salt`,
  `password_algo`, `password_ver`, `account_status`, `token_version`
)
SELECT
  @admin_user_id, @admin_phone, @admin_email, @password_hash, @password_salt,
  'argon2id', 1, 1, 1
FROM DUAL
WHERE NOT EXISTS (
  SELECT 1 FROM `iam_user_auth` WHERE `phone` = @admin_phone
);

-- Always normalize key flags to active.
UPDATE `iam_user_auth`
SET
  `account_status` = 1,
  `password_algo` = 'argon2id',
  `password_ver` = 1
WHERE `phone` = @admin_phone;

SET @admin_user_id := (
  SELECT `user_id`
  FROM `iam_user_auth`
  WHERE `phone` = @admin_phone
  LIMIT 1
);

-- 3) Ensure role dictionaries exist (safe if 0003 already ran).
INSERT INTO `iam_role` (`role_code`, `role_key`, `role_name`, `status`) VALUES
  (5, 'SUPER_ADMIN', 'Super Admin', 1),
  (6, 'AUDITOR', 'Auditor', 1),
  (7, 'OPS_ANALYST', 'Operations Analyst', 1),
  (4, 'CUSTOMER_SERVICE', 'Customer Service', 1)
ON DUPLICATE KEY UPDATE
  `role_key` = VALUES(`role_key`),
  `role_name` = VALUES(`role_name`),
  `status` = VALUES(`status`);

-- 4) Grant SUPER_ADMIN (permission-point driven; role only as permission carrier).
INSERT INTO `iam_user_role` (`user_id`, `role_code`, `scope_type`, `scope_id`, `status`)
VALUES (@admin_user_id, 5, 1, 0, 1)
ON DUPLICATE KEY UPDATE
  `status` = VALUES(`status`);

-- 5) Optional: grant additional admin roles to the same account.
-- INSERT INTO `iam_user_role` (`user_id`, `role_code`, `scope_type`, `scope_id`, `status`)
-- VALUES (@admin_user_id, 6, 1, 0, 1), (@admin_user_id, 7, 1, 0, 1)
-- ON DUPLICATE KEY UPDATE `status` = VALUES(`status`);

-- 6) Verify.
SELECT
  a.`user_id`,
  a.`phone`,
  a.`email`,
  a.`account_status`,
  GROUP_CONCAT(r.`role_code` ORDER BY r.`role_code`) AS role_codes
FROM `iam_user_auth` a
LEFT JOIN `iam_user_role` r
  ON r.`user_id` = a.`user_id`
 AND r.`status` = 1
WHERE a.`phone` = @admin_phone
GROUP BY a.`user_id`, a.`phone`, a.`email`, a.`account_status`;
