// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/order-svc/internal/dao/internal"
)

// orderPaymentDao is the data access object for the table order_payment.
// You can define custom methods on it to extend its functionality as needed.
type orderPaymentDao struct {
	*internal.OrderPaymentDao
}

var (
	// OrderPayment is a globally accessible object for table order_payment operations.
	OrderPayment = orderPaymentDao{internal.NewOrderPaymentDao()}
)

// Add your custom methods and functionality below.
