// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/order-svc/internal/dao/internal"
)

// orderOperateLogDao is the data access object for the table order_operate_log.
// You can define custom methods on it to extend its functionality as needed.
type orderOperateLogDao struct {
	*internal.OrderOperateLogDao
}

var (
	// OrderOperateLog is a globally accessible object for table order_operate_log operations.
	OrderOperateLog = orderOperateLogDao{internal.NewOrderOperateLogDao()}
)

// Add your custom methods and functionality below.
