// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/order-svc/internal/dao/internal"
)

// orderPointsCompensationTaskDao is the data access object for the table order_points_compensation_task.
// You can define custom methods on it to extend its functionality as needed.
type orderPointsCompensationTaskDao struct {
	*internal.OrderPointsCompensationTaskDao
}

var (
	// OrderPointsCompensationTask is a globally accessible object for table order_points_compensation_task operations.
	OrderPointsCompensationTask = orderPointsCompensationTaskDao{internal.NewOrderPointsCompensationTaskDao()}
)

// Add your custom methods and functionality below.
