// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/order-svc/internal/dao/internal"
)

// orderSubDao is the data access object for the table order_sub.
// You can define custom methods on it to extend its functionality as needed.
type orderSubDao struct {
	*internal.OrderSubDao
}

var (
	// OrderSub is a globally accessible object for table order_sub operations.
	OrderSub = orderSubDao{internal.NewOrderSubDao()}
)

// Add your custom methods and functionality below.
