// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/order-svc/internal/dao/internal"
)

// orderAddressSnapshotDao is the data access object for the table order_address_snapshot.
// You can define custom methods on it to extend its functionality as needed.
type orderAddressSnapshotDao struct {
	*internal.OrderAddressSnapshotDao
}

var (
	// OrderAddressSnapshot is a globally accessible object for table order_address_snapshot operations.
	OrderAddressSnapshot = orderAddressSnapshotDao{internal.NewOrderAddressSnapshotDao()}
)

// Add your custom methods and functionality below.
