// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/order-svc/internal/dao/internal"
)

// orderMainDao is the data access object for the table order_main.
// You can define custom methods on it to extend its functionality as needed.
type orderMainDao struct {
	*internal.OrderMainDao
}

var (
	// OrderMain is a globally accessible object for table order_main operations.
	OrderMain = orderMainDao{internal.NewOrderMainDao()}
)

// Add your custom methods and functionality below.
