// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/order-svc/internal/dao/internal"
)

// orderOutboxEventDao is the data access object for the table order_outbox_event.
// You can define custom methods on it to extend its functionality as needed.
type orderOutboxEventDao struct {
	*internal.OrderOutboxEventDao
}

var (
	// OrderOutboxEvent is a globally accessible object for table order_outbox_event operations.
	OrderOutboxEvent = orderOutboxEventDao{internal.NewOrderOutboxEventDao()}
)

// Add your custom methods and functionality below.
