// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/order-svc/internal/dao/internal"
)

// orderInventoryLinkDao is the data access object for the table order_inventory_link.
// You can define custom methods on it to extend its functionality as needed.
type orderInventoryLinkDao struct {
	*internal.OrderInventoryLinkDao
}

var (
	// OrderInventoryLink is a globally accessible object for table order_inventory_link operations.
	OrderInventoryLink = orderInventoryLinkDao{internal.NewOrderInventoryLinkDao()}
)

// Add your custom methods and functionality below.
