// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/order-svc/internal/dao/internal"
)

// orderIdempotencyDao is the data access object for the table order_idempotency.
// You can define custom methods on it to extend its functionality as needed.
type orderIdempotencyDao struct {
	*internal.OrderIdempotencyDao
}

var (
	// OrderIdempotency is a globally accessible object for table order_idempotency operations.
	OrderIdempotency = orderIdempotencyDao{internal.NewOrderIdempotencyDao()}
)

// Add your custom methods and functionality below.
