// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/media-svc/internal/dao/internal"
)

// mediaOutboxEventDao is the data access object for the table media_outbox_event.
// You can define custom methods on it to extend its functionality as needed.
type mediaOutboxEventDao struct {
	*internal.MediaOutboxEventDao
}

var (
	// MediaOutboxEvent is a globally accessible object for table media_outbox_event operations.
	MediaOutboxEvent = mediaOutboxEventDao{internal.NewMediaOutboxEventDao()}
)

// Add your custom methods and functionality below.
