// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/media-svc/internal/dao/internal"
)

// mediaIdempotencyDao 是 media_idempotency 表的数据访问对象。
// 可在其上定义自定义方法以扩展功能。
type mediaIdempotencyDao struct {
	*internal.MediaIdempotencyDao
}

var (
	// MediaIdempotency 是用于 media_idempotency 表操作的全局对象。
	MediaIdempotency = mediaIdempotencyDao{internal.NewMediaIdempotencyDao()}
)

// 在下方添加自定义方法和功能。
