// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/media-svc/internal/dao/internal"
)

// mediaScenePolicyDao is the data access object for the table media_scene_policy.
// You can define custom methods on it to extend its functionality as needed.
type mediaScenePolicyDao struct {
	*internal.MediaScenePolicyDao
}

var (
	// MediaScenePolicy is a globally accessible object for table media_scene_policy operations.
	MediaScenePolicy = mediaScenePolicyDao{internal.NewMediaScenePolicyDao()}
)

// Add your custom methods and functionality below.
