// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/media-svc/internal/dao/internal"
)

// mediaIdempotencyDao is the data access object for the table media_idempotency.
// You can define custom methods on it to extend its functionality as needed.
type mediaIdempotencyDao struct {
	*internal.MediaIdempotencyDao
}

var (
	// MediaIdempotency is a globally accessible object for table media_idempotency operations.
	MediaIdempotency = mediaIdempotencyDao{internal.NewMediaIdempotencyDao()}
)

// Add your custom methods and functionality below.
