// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/media-svc/internal/dao/internal"
)

// mediaAssetBindingDao is the data access object for the table media_asset_binding.
// You can define custom methods on it to extend its functionality as needed.
type mediaAssetBindingDao struct {
	*internal.MediaAssetBindingDao
}

var (
	// MediaAssetBinding is a globally accessible object for table media_asset_binding operations.
	MediaAssetBinding = mediaAssetBindingDao{internal.NewMediaAssetBindingDao()}
)

// Add your custom methods and functionality below.
