// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/media-svc/internal/dao/internal"
)

// mediaAssetDao 是 media_asset 表的数据访问对象。
// 可在其上定义自定义方法以扩展功能。
type mediaAssetDao struct {
	*internal.MediaAssetDao
}

var (
	// MediaAsset 是用于 media_asset 表操作的全局对象。
	MediaAsset = mediaAssetDao{internal.NewMediaAssetDao()}
)

// 在下方添加自定义方法和功能。
