// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/media-svc/internal/dao/internal"
)

// mediaOutboxEventArchiveDao is the data access object for the table media_outbox_event_archive.
// You can define custom methods on it to extend its functionality as needed.
type mediaOutboxEventArchiveDao struct {
	*internal.MediaOutboxEventArchiveDao
}

var (
	// MediaOutboxEventArchive is a globally accessible object for table media_outbox_event_archive operations.
	MediaOutboxEventArchive = mediaOutboxEventArchiveDao{internal.NewMediaOutboxEventArchiveDao()}
)

// Add your custom methods and functionality below.
