// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/media-svc/internal/dao/internal"
)

// mediaConsumerEventDedupDao is the data access object for the table media_consumer_event_dedup.
// You can define custom methods on it to extend its functionality as needed.
type mediaConsumerEventDedupDao struct {
	*internal.MediaConsumerEventDedupDao
}

var (
	// MediaConsumerEventDedup is a globally accessible object for table media_consumer_event_dedup operations.
	MediaConsumerEventDedup = mediaConsumerEventDedupDao{internal.NewMediaConsumerEventDedupDao()}
)

// Add your custom methods and functionality below.
