// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/media-svc/internal/dao/internal"
)

// mediaConsumerEventDedupDao 是 media_consumer_event_dedup 表的数据访问对象。
// 可在其上定义自定义方法以扩展功能。
type mediaConsumerEventDedupDao struct {
	*internal.MediaConsumerEventDedupDao
}

var (
	// MediaConsumerEventDedup 是用于 media_consumer_event_dedup 表操作的全局对象。
	MediaConsumerEventDedup = mediaConsumerEventDedupDao{internal.NewMediaConsumerEventDedupDao()}
)

// 在下方添加自定义方法和功能。
