// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/media-svc/internal/dao/internal"
)

// mediaOutboxEventArchiveDao 是 media_outbox_event_archive 表的数据访问对象。
// 可在其上定义自定义方法以扩展功能。
type mediaOutboxEventArchiveDao struct {
	*internal.MediaOutboxEventArchiveDao
}

var (
	// MediaOutboxEventArchive 是用于 media_outbox_event_archive 表操作的全局对象。
	MediaOutboxEventArchive = mediaOutboxEventArchiveDao{internal.NewMediaOutboxEventArchiveDao()}
)

// 在下方添加自定义方法和功能。
