// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/media-svc/internal/dao/internal"
)

// mediaAssetDao is the data access object for the table media_asset.
// You can define custom methods on it to extend its functionality as needed.
type mediaAssetDao struct {
	*internal.MediaAssetDao
}

var (
	// MediaAsset is a globally accessible object for table media_asset operations.
	MediaAsset = mediaAssetDao{internal.NewMediaAssetDao()}
)

// Add your custom methods and functionality below.
