// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/seller-shop-svc/internal/dao/internal"
)

// sellerShopOpLogDao is the data access object for the table seller_shop_op_log.
// You can define custom methods on it to extend its functionality as needed.
type sellerShopOpLogDao struct {
	*internal.SellerShopOpLogDao
}

var (
	// SellerShopOpLog is a globally accessible object for table seller_shop_op_log operations.
	SellerShopOpLog = sellerShopOpLogDao{internal.NewSellerShopOpLogDao()}
)

// Add your custom methods and functionality below.
