// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/seller-shop-svc/internal/dao/internal"
)

// sellerOutboxEventDao is the data access object for the table seller_outbox_event.
// You can define custom methods on it to extend its functionality as needed.
type sellerOutboxEventDao struct {
	*internal.SellerOutboxEventDao
}

var (
	// SellerOutboxEvent is a globally accessible object for table seller_outbox_event operations.
	SellerOutboxEvent = sellerOutboxEventDao{internal.NewSellerOutboxEventDao()}
)

// Add your custom methods and functionality below.
