// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/seller-shop-svc/internal/dao/internal"
)

// sellerApplicationDao is the data access object for the table seller_application.
// You can define custom methods on it to extend its functionality as needed.
type sellerApplicationDao struct {
	*internal.SellerApplicationDao
}

var (
	// SellerApplication is a globally accessible object for table seller_application operations.
	SellerApplication = sellerApplicationDao{internal.NewSellerApplicationDao()}
)

// Add your custom methods and functionality below.
