// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/seller-shop-svc/internal/dao/internal"
)

// sellerOutboxEventArchiveDao is the data access object for the table seller_outbox_event_archive.
// You can define custom methods on it to extend its functionality as needed.
type sellerOutboxEventArchiveDao struct {
	*internal.SellerOutboxEventArchiveDao
}

var (
	// SellerOutboxEventArchive is a globally accessible object for table seller_outbox_event_archive operations.
	SellerOutboxEventArchive = sellerOutboxEventArchiveDao{internal.NewSellerOutboxEventArchiveDao()}
)

// Add your custom methods and functionality below.
