// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/seller-shop-svc/internal/dao/internal"
)

// sellerConsumerEventDedupDao is the data access object for the table seller_consumer_event_dedup.
// You can define custom methods on it to extend its functionality as needed.
type sellerConsumerEventDedupDao struct {
	*internal.SellerConsumerEventDedupDao
}

var (
	// SellerConsumerEventDedup is a globally accessible object for table seller_consumer_event_dedup operations.
	SellerConsumerEventDedup = sellerConsumerEventDedupDao{internal.NewSellerConsumerEventDedupDao()}
)

// Add your custom methods and functionality below.
