// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/seller-shop-svc/internal/dao/internal"
)

// sellerApplicationDao 是 seller_application 表的数据访问对象，可在此定义自定义方法扩展功能。

type sellerApplicationDao struct {
	*internal.SellerApplicationDao
}

var (
// SellerApplication 是 seller_application 表操作的全局访问对象。
	SellerApplication = sellerApplicationDao{internal.NewSellerApplicationDao()}
)

// 在此处添加自定义方法和功能。


