// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/seller-shop-svc/internal/dao/internal"
)

// sellerShopDao is the data access object for the table seller_shop.
// You can define custom methods on it to extend its functionality as needed.
type sellerShopDao struct {
	*internal.SellerShopDao
}

var (
	// SellerShop is a globally accessible object for table seller_shop operations.
	SellerShop = sellerShopDao{internal.NewSellerShopDao()}
)

// Add your custom methods and functionality below.
