// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/seller-shop-svc/internal/dao/internal"
)

// sellerEntityDao is the data access object for the table seller_entity.
// You can define custom methods on it to extend its functionality as needed.
type sellerEntityDao struct {
	*internal.SellerEntityDao
}

var (
	// SellerEntity is a globally accessible object for table seller_entity operations.
	SellerEntity = sellerEntityDao{internal.NewSellerEntityDao()}
)

// Add your custom methods and functionality below.
