// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/seller-shop-svc/internal/dao/internal"
)

// sellerShopNameRegistryDao is the data access object for the table seller_shop_name_registry.
// You can define custom methods on it to extend its functionality as needed.
type sellerShopNameRegistryDao struct {
	*internal.SellerShopNameRegistryDao
}

var (
	// SellerShopNameRegistry is a globally accessible object for table seller_shop_name_registry operations.
	SellerShopNameRegistry = sellerShopNameRegistryDao{internal.NewSellerShopNameRegistryDao()}
)

// Add your custom methods and functionality below.
