// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/seller-shop-svc/internal/dao/internal"
)

// sellerApplicationOpLogDao is the data access object for the table seller_application_op_log.
// You can define custom methods on it to extend its functionality as needed.
type sellerApplicationOpLogDao struct {
	*internal.SellerApplicationOpLogDao
}

var (
	// SellerApplicationOpLog is a globally accessible object for table seller_application_op_log operations.
	SellerApplicationOpLog = sellerApplicationOpLogDao{internal.NewSellerApplicationOpLogDao()}
)

// Add your custom methods and functionality below.
