// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/seller-shop-svc/internal/dao/internal"
)

// sellerIdempotencyDao is the data access object for the table seller_idempotency.
// You can define custom methods on it to extend its functionality as needed.
type sellerIdempotencyDao struct {
	*internal.SellerIdempotencyDao
}

var (
	// SellerIdempotency is a globally accessible object for table seller_idempotency operations.
	SellerIdempotency = sellerIdempotencyDao{internal.NewSellerIdempotencyDao()}
)

// Add your custom methods and functionality below.
