// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/seller-shop-svc/internal/dao/internal"
)

// sellerEntityDocDao is the data access object for the table seller_entity_doc.
// You can define custom methods on it to extend its functionality as needed.
type sellerEntityDocDao struct {
	*internal.SellerEntityDocDao
}

var (
	// SellerEntityDoc is a globally accessible object for table seller_entity_doc operations.
	SellerEntityDoc = sellerEntityDocDao{internal.NewSellerEntityDocDao()}
)

// Add your custom methods and functionality below.
