// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/seller-shop-svc/internal/dao/internal"
)

// shopStoreCategoryProductDao is the data access object for the table shop_store_category_product.
// You can define custom methods on it to extend its functionality as needed.
type shopStoreCategoryProductDao struct {
	*internal.ShopStoreCategoryProductDao
}

var (
	// ShopStoreCategoryProduct is a globally accessible object for table shop_store_category_product operations.
	ShopStoreCategoryProduct = shopStoreCategoryProductDao{internal.NewShopStoreCategoryProductDao()}
)

// Add your custom methods and functionality below.
