// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/seller-shop-svc/internal/dao/internal"
)

// shopStoreCategoryDao is the data access object for the table shop_store_category.
// You can define custom methods on it to extend its functionality as needed.
type shopStoreCategoryDao struct {
	*internal.ShopStoreCategoryDao
}

var (
	// ShopStoreCategory is a globally accessible object for table shop_store_category operations.
	ShopStoreCategory = shopStoreCategoryDao{internal.NewShopStoreCategoryDao()}
)

// Add your custom methods and functionality below.
