CREATE DATABASE IF NOT EXISTS shopa_risk_svc CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE shopa_risk_svc;

CREATE TABLE IF NOT EXISTS risk_rule (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  rule_code VARCHAR(64) NOT NULL,
  rule_name VARCHAR(128) NOT NULL,
  enabled TINYINT UNSIGNED NOT NULL DEFAULT 1,
  priority INT UNSIGNED NOT NULL DEFAULT 100,
  latest_version BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_rule_code(rule_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS risk_rule_version (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  rule_code VARCHAR(64) NOT NULL,
  version_no BIGINT UNSIGNED NOT NULL,
  rule_expr_json MEDIUMTEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_rule_version(rule_code, version_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS risk_event_inbox (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  event_id VARCHAR(128) NOT NULL,
  event_type VARCHAR(64) NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  biz_no VARCHAR(64) NOT NULL DEFAULT '',
  payload_json MEDIUMTEXT,
  occurred_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_event_id(event_id),
  KEY idx_user_created(user_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS risk_feature_snapshot (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  risk_score INT UNSIGNED NOT NULL DEFAULT 0,
  feature_json MEDIUMTEXT,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_user_id(user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS risk_decision_log (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  decision_no VARCHAR(64) NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  biz_type VARCHAR(64) NOT NULL,
  biz_no VARCHAR(64) NOT NULL,
  decision TINYINT UNSIGNED NOT NULL DEFAULT 0,
  risk_score INT UNSIGNED NOT NULL DEFAULT 0,
  reason_codes_json TEXT,
  degraded TINYINT UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_decision_no(decision_no),
  KEY idx_user_created(user_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS risk_hit_log (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  hit_no VARCHAR(64) NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  rule_code VARCHAR(64) NOT NULL,
  biz_type VARCHAR(64) NOT NULL,
  biz_no VARCHAR(64) NOT NULL,
  decision TINYINT UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_hit_no(hit_no),
  KEY idx_user_created(user_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS risk_whitelist (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  target_type VARCHAR(32) NOT NULL,
  target_value VARCHAR(128) NOT NULL,
  reason VARCHAR(255) NOT NULL DEFAULT '',
  enabled TINYINT UNSIGNED NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_target(target_type, target_value)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS risk_outbox_event (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  event_id VARCHAR(64) NOT NULL,
  aggregate_type VARCHAR(64) NOT NULL,
  aggregate_id VARCHAR(64) NOT NULL,
  event_type VARCHAR(128) NOT NULL,
  payload_json MEDIUMTEXT,
  status TINYINT UNSIGNED NOT NULL DEFAULT 0,
  retry_count INT UNSIGNED NOT NULL DEFAULT 0,
  next_retry_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_event_id(event_id),
  KEY idx_status_next_retry(status, next_retry_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
