CREATE TABLE IF NOT EXISTS `agent_conversation` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `conversation_no` VARCHAR(64) NOT NULL,
  `user_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `bot_code` VARCHAR(64) NOT NULL DEFAULT '',
  `scene_code` VARCHAR(64) NOT NULL DEFAULT '',
  `shop_no` VARCHAR(64) NOT NULL DEFAULT '',
  `order_no` VARCHAR(64) NOT NULL DEFAULT '',
  `sub_order_no` VARCHAR(64) NOT NULL DEFAULT '',
  `anchor_spu_no` VARCHAR(64) NOT NULL DEFAULT '',
  `anchor_sku_no` VARCHAR(64) NOT NULL DEFAULT '',
  `conversation_status_code` VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
  `last_run_status_code` VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  `is_human_handover` TINYINT(1) NOT NULL DEFAULT 0,
  `pending_message_count` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `session_summary` TEXT NULL,
  `session_summary_version` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `last_summarized_message_no` VARCHAR(64) NOT NULL DEFAULT '',
  `last_message_at` DATETIME NULL,
  `last_queue_notice_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_conversation_no` (`conversation_no`),
  KEY `idx_user_status` (`user_id`, `conversation_status_code`, `id`),
  KEY `idx_scene_shop` (`scene_code`, `shop_no`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `agent_message` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `message_no` VARCHAR(64) NOT NULL,
  `conversation_no` VARCHAR(64) NOT NULL,
  `run_no` VARCHAR(64) NOT NULL DEFAULT '',
  `reply_to_turn_no` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `sender_type_code` VARCHAR(32) NOT NULL DEFAULT '',
  `message_type_code` VARCHAR(32) NOT NULL DEFAULT '',
  `client_message_no` VARCHAR(64) NOT NULL DEFAULT '',
  `content_text` TEXT NULL,
  `asset_ids_json` JSON NULL,
  `ext_json` JSON NULL,
  `interrupted` TINYINT(1) NOT NULL DEFAULT 0,
  `sent_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_message_no` (`message_no`),
  UNIQUE KEY `uniq_conversation_client_msg` (`conversation_no`, `client_message_no`),
  KEY `idx_conversation_id` (`conversation_no`, `id`),
  KEY `idx_run_no` (`run_no`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `agent_run` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `run_no` VARCHAR(64) NOT NULL,
  `conversation_no` VARCHAR(64) NOT NULL,
  `user_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `shop_no` VARCHAR(64) NOT NULL DEFAULT '',
  `subject_user_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `subject_shop_no` VARCHAR(64) NOT NULL DEFAULT '',
  `turn_no` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `accepted_status_code` VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  `run_status_code` VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  `current_node_code` VARCHAR(64) NOT NULL DEFAULT '',
  `graph_state_json` JSON NULL,
  `checkpoint_version` BIGINT UNSIGNED NOT NULL DEFAULT 1,
  `tool_wait_timeout_at` DATETIME NULL,
  `tool_result_status` VARCHAR(32) NOT NULL DEFAULT 'UNSPECIFIED',
  `degraded_reason_code` VARCHAR(64) NOT NULL DEFAULT '',
  `queue_blocked` TINYINT(1) NOT NULL DEFAULT 0,
  `queue_hint_message` VARCHAR(512) NOT NULL DEFAULT '',
  `risk_decision_code` VARCHAR(32) NOT NULL DEFAULT 'PASS',
  `prompt_injection_flag` TINYINT(1) NOT NULL DEFAULT 0,
  `reply_interrupted` TINYINT(1) NOT NULL DEFAULT 0,
  `interrupt_reason_code` VARCHAR(32) NOT NULL DEFAULT '',
  `merged_message_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `tool_iteration_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `tool_call_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `prompt_token_estimate` INT UNSIGNED NOT NULL DEFAULT 0,
  `completion_token_estimate` INT UNSIGNED NOT NULL DEFAULT 0,
  `answer_sources_json` JSON NULL,
  `error_code` VARCHAR(64) NOT NULL DEFAULT '',
  `error_message` VARCHAR(512) NOT NULL DEFAULT '',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `started_at` DATETIME NULL,
  `finished_at` DATETIME NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_run_no` (`run_no`),
  KEY `idx_conversation_turn` (`conversation_no`, `turn_no`),
  KEY `idx_user_created` (`user_id`, `created_at`),
  KEY `idx_run_status_timeout` (`run_status_code`, `tool_wait_timeout_at`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `agent_knowledge_doc` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `knowledge_doc_no` VARCHAR(64) NOT NULL,
  `title` VARCHAR(256) NOT NULL DEFAULT '',
  `knowledge_scope_code` VARCHAR(32) NOT NULL DEFAULT '',
  `source_type_code` VARCHAR(64) NOT NULL DEFAULT '',
  `source_id` VARCHAR(128) NOT NULL DEFAULT '',
  `source_version` BIGINT UNSIGNED NOT NULL DEFAULT 1,
  `shop_no` VARCHAR(64) NOT NULL DEFAULT '',
  `content_type_code` VARCHAR(32) NOT NULL DEFAULT '',
  `content_text` MEDIUMTEXT NULL,
  `asset_ids_json` JSON NULL,
  `tags_json` JSON NULL,
  `status_code` VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
  `reject_reason_code` VARCHAR(64) NOT NULL DEFAULT '',
  `reject_comment` VARCHAR(512) NOT NULL DEFAULT '',
  `version` BIGINT UNSIGNED NOT NULL DEFAULT 1,
  `published_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_knowledge_doc_no` (`knowledge_doc_no`),
  KEY `idx_scope_status` (`knowledge_scope_code`, `status_code`, `id`),
  KEY `idx_source` (`source_type_code`, `source_id`, `source_version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `agent_knowledge_chunk` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `chunk_no` VARCHAR(64) NOT NULL,
  `knowledge_doc_no` VARCHAR(64) NOT NULL,
  `source_type_code` VARCHAR(64) NOT NULL DEFAULT '',
  `source_id` VARCHAR(128) NOT NULL DEFAULT '',
  `source_version` BIGINT UNSIGNED NOT NULL DEFAULT 1,
  `chunk_index` INT UNSIGNED NOT NULL DEFAULT 0,
  `chunk_text` MEDIUMTEXT NOT NULL,
  `chunk_text_preview` VARCHAR(512) NOT NULL DEFAULT '',
  `vector_document_id` VARCHAR(128) NOT NULL DEFAULT '',
  `metadata_json` JSON NULL,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `index_status_code` VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_chunk_no` (`chunk_no`),
  UNIQUE KEY `uniq_doc_chunk_index` (`knowledge_doc_no`, `chunk_index`),
  KEY `idx_source_version` (`source_type_code`, `source_id`, `source_version`, `is_deleted`),
  KEY `idx_doc_status` (`knowledge_doc_no`, `index_status_code`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `agent_escalation_ticket` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ticket_no` VARCHAR(64) NOT NULL,
  `conversation_no` VARCHAR(64) NOT NULL,
  `user_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `shop_no` VARCHAR(64) NOT NULL DEFAULT '',
  `run_no` VARCHAR(64) NOT NULL DEFAULT '',
  `escalation_reason_code` VARCHAR(64) NOT NULL DEFAULT '',
  `status_code` VARCHAR(32) NOT NULL DEFAULT 'ESCALATION_PENDING',
  `handoff_summary` VARCHAR(1024) NOT NULL DEFAULT '',
  `handoff_summary_status_code` VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  `operator_user_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `remark` VARCHAR(512) NOT NULL DEFAULT '',
  `queue_appendix_json` JSON NULL,
  `handoff_generated_at` DATETIME NULL,
  `accepted_at` DATETIME NULL,
  `closed_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_ticket_no` (`ticket_no`),
  KEY `idx_conversation_status` (`conversation_no`, `status_code`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `agent_feedback` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `conversation_no` VARCHAR(64) NOT NULL,
  `run_no` VARCHAR(64) NOT NULL,
  `user_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `shop_no` VARCHAR(64) NOT NULL DEFAULT '',
  `feedback_code` VARCHAR(32) NOT NULL DEFAULT '',
  `resolved` TINYINT(1) NOT NULL DEFAULT 0,
  `comment` VARCHAR(512) NOT NULL DEFAULT '',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  KEY `idx_run_user` (`run_no`, `user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `agent_tool_call_log` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `conversation_no` VARCHAR(64) NOT NULL,
  `run_no` VARCHAR(64) NOT NULL,
  `tool_name` VARCHAR(64) NOT NULL DEFAULT '',
  `adapter_code` VARCHAR(64) NOT NULL DEFAULT '',
  `tool_scope_code` VARCHAR(32) NOT NULL DEFAULT 'UNSPECIFIED',
  `subject_user_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `subject_shop_no` VARCHAR(64) NOT NULL DEFAULT '',
  `request_payload_json` JSON NULL,
  `response_payload_json` JSON NULL,
  `tool_result_status` VARCHAR(32) NOT NULL DEFAULT 'UNSPECIFIED',
  `degraded_reason_code` VARCHAR(64) NOT NULL DEFAULT '',
  `error_code` VARCHAR(64) NOT NULL DEFAULT '',
  `error_message` VARCHAR(512) NOT NULL DEFAULT '',
  `duration_ms` INT UNSIGNED NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_run_tool` (`run_no`, `tool_name`, `id`),
  KEY `idx_subject_scope` (`subject_user_id`, `subject_shop_no`, `tool_scope_code`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `agent_idempotency` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idempotency_key` VARCHAR(128) NOT NULL,
  `scope_code` VARCHAR(32) NOT NULL DEFAULT '',
  `scope_id` VARCHAR(128) NOT NULL DEFAULT '',
  `response_json` JSON NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_idempotency_scope` (`idempotency_key`, `scope_code`, `scope_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
