// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/fulfillment-svc/internal/dao/internal"
)

// fulfillmentIdempotencyDao is the data access object for the table fulfillment_idempotency.
// You can define custom methods on it to extend its functionality as needed.
type fulfillmentIdempotencyDao struct {
	*internal.FulfillmentIdempotencyDao
}

var (
	// FulfillmentIdempotency is a globally accessible object for table fulfillment_idempotency operations.
	FulfillmentIdempotency = fulfillmentIdempotencyDao{internal.NewFulfillmentIdempotencyDao()}
)

// Add your custom methods and functionality below.
