// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/fulfillment-svc/internal/dao/internal"
)

// fulfillmentOutboxEventDao is the data access object for the table fulfillment_outbox_event.
// You can define custom methods on it to extend its functionality as needed.
type fulfillmentOutboxEventDao struct {
	*internal.FulfillmentOutboxEventDao
}

var (
	// FulfillmentOutboxEvent is a globally accessible object for table fulfillment_outbox_event operations.
	FulfillmentOutboxEvent = fulfillmentOutboxEventDao{internal.NewFulfillmentOutboxEventDao()}
)

// Add your custom methods and functionality below.
