// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/fulfillment-svc/internal/dao/internal"
)

// fulfillmentShipmentDao is the data access object for the table fulfillment_shipment.
// You can define custom methods on it to extend its functionality as needed.
type fulfillmentShipmentDao struct {
	*internal.FulfillmentShipmentDao
}

var (
	// FulfillmentShipment is a globally accessible object for table fulfillment_shipment operations.
	FulfillmentShipment = fulfillmentShipmentDao{internal.NewFulfillmentShipmentDao()}
)

// Add your custom methods and functionality below.
