// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/fulfillment-svc/internal/dao/internal"
)

// fulfillmentTrackingNodeDao is the data access object for the table fulfillment_tracking_node.
// You can define custom methods on it to extend its functionality as needed.
type fulfillmentTrackingNodeDao struct {
	*internal.FulfillmentTrackingNodeDao
}

var (
	// FulfillmentTrackingNode is a globally accessible object for table fulfillment_tracking_node operations.
	FulfillmentTrackingNode = fulfillmentTrackingNodeDao{internal.NewFulfillmentTrackingNodeDao()}
)

// Add your custom methods and functionality below.
