// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/fulfillment-svc/internal/dao/internal"
)

// fulfillmentOperateLogDao is the data access object for the table fulfillment_operate_log.
// You can define custom methods on it to extend its functionality as needed.
type fulfillmentOperateLogDao struct {
	*internal.FulfillmentOperateLogDao
}

var (
	// FulfillmentOperateLog is a globally accessible object for table fulfillment_operate_log operations.
	FulfillmentOperateLog = fulfillmentOperateLogDao{internal.NewFulfillmentOperateLogDao()}
)

// Add your custom methods and functionality below.
