// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/catalog-svc/internal/dao/internal"
)

// catalogAttributeTemplateDao is the data access object for the table catalog_attribute_template.
// You can define custom methods on it to extend its functionality as needed.
type catalogAttributeTemplateDao struct {
	*internal.CatalogAttributeTemplateDao
}

var (
	// CatalogAttributeTemplate is a globally accessible object for table catalog_attribute_template operations.
	CatalogAttributeTemplate = catalogAttributeTemplateDao{internal.NewCatalogAttributeTemplateDao()}
)

// Add your custom methods and functionality below.
