// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/catalog-svc/internal/dao/internal"
)

// catalogReviewTaskDao 是 catalog_review_task 表的数据访问对象。
// 可根据需要在其上添加自定义方法以扩展能力。
type catalogReviewTaskDao struct {
	*internal.CatalogReviewTaskDao
}

var (
	// CatalogReviewTask 为 catalog_review_task 表操作提供全局可用的 DAO 对象。
	CatalogReviewTask = catalogReviewTaskDao{internal.NewCatalogReviewTaskDao()}
)

// 在下方添加自定义方法与扩展功能。
