// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/catalog-svc/internal/dao/internal"
)

// catalogOutboxEventArchiveDao 是 catalog_outbox_event_archive 表的数据访问对象。
// 可根据需要在其上添加自定义方法以扩展能力。
type catalogOutboxEventArchiveDao struct {
	*internal.CatalogOutboxEventArchiveDao
}

var (
	// CatalogOutboxEventArchive 为 catalog_outbox_event_archive 表操作提供全局可用的 DAO 对象。
	CatalogOutboxEventArchive = catalogOutboxEventArchiveDao{internal.NewCatalogOutboxEventArchiveDao()}
)

// 在下方添加自定义方法与扩展功能。
