// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/catalog-svc/internal/dao/internal"
)

// catalogSpuAttrValueDao is the data access object for the table catalog_spu_attr_value.
// You can define custom methods on it to extend its functionality as needed.
type catalogSpuAttrValueDao struct {
	*internal.CatalogSpuAttrValueDao
}

var (
	// CatalogSpuAttrValue is a globally accessible object for table catalog_spu_attr_value operations.
	CatalogSpuAttrValue = catalogSpuAttrValueDao{internal.NewCatalogSpuAttrValueDao()}
)

// Add your custom methods and functionality below.
