// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/catalog-svc/internal/dao/internal"
)

// catalogOutboxEventDao is the data access object for the table catalog_outbox_event.
// You can define custom methods on it to extend its functionality as needed.
type catalogOutboxEventDao struct {
	*internal.CatalogOutboxEventDao
}

var (
	// CatalogOutboxEvent is a globally accessible object for table catalog_outbox_event operations.
	CatalogOutboxEvent = catalogOutboxEventDao{internal.NewCatalogOutboxEventDao()}
)

// Add your custom methods and functionality below.
