// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/catalog-svc/internal/dao/internal"
)

// catalogOutboxEventDao 是 catalog_outbox_event 表的 DAO。
// 可按需在其上定义自定义方法以扩展其功能。
type catalogOutboxEventDao struct {
	*internal.CatalogOutboxEventDao
}

var (
	// CatalogOutboxEvent 为 catalog_outbox_event 表操作提供全局访问对象。
	CatalogOutboxEvent = catalogOutboxEventDao{internal.NewCatalogOutboxEventDao()}
)

// 在此处扩展自定义方法和功能。
