// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/catalog-svc/internal/dao/internal"
)

// catalogBrandDao is the data access object for the table catalog_brand.
// You can define custom methods on it to extend its functionality as needed.
type catalogBrandDao struct {
	*internal.CatalogBrandDao
}

var (
	// CatalogBrand is a globally accessible object for table catalog_brand operations.
	CatalogBrand = catalogBrandDao{internal.NewCatalogBrandDao()}
)

// Add your custom methods and functionality below.
