// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/catalog-svc/internal/dao/internal"
)

// catalogSpuDao is the data access object for the table catalog_spu.
// You can define custom methods on it to extend its functionality as needed.
type catalogSpuDao struct {
	*internal.CatalogSpuDao
}

var (
	// CatalogSpu is a globally accessible object for table catalog_spu operations.
	CatalogSpu = catalogSpuDao{internal.NewCatalogSpuDao()}
)

// Add your custom methods and functionality below.
