// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/catalog-svc/internal/dao/internal"
)

// catalogCategoryDao is the data access object for the table catalog_category.
// You can define custom methods on it to extend its functionality as needed.
type catalogCategoryDao struct {
	*internal.CatalogCategoryDao
}

var (
	// CatalogCategory is a globally accessible object for table catalog_category operations.
	CatalogCategory = catalogCategoryDao{internal.NewCatalogCategoryDao()}
)

// Add your custom methods and functionality below.
