// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/catalog-svc/internal/dao/internal"
)

// catalogSkuSaleAttrValueDao is the data access object for the table catalog_sku_sale_attr_value.
// You can define custom methods on it to extend its functionality as needed.
type catalogSkuSaleAttrValueDao struct {
	*internal.CatalogSkuSaleAttrValueDao
}

var (
	// CatalogSkuSaleAttrValue is a globally accessible object for table catalog_sku_sale_attr_value operations.
	CatalogSkuSaleAttrValue = catalogSkuSaleAttrValueDao{internal.NewCatalogSkuSaleAttrValueDao()}
)

// Add your custom methods and functionality below.
