// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/catalog-svc/internal/dao/internal"
)

// catalogAttributeTemplateDao 是 catalog_attribute_template 表的 DAO。
// 可按需在其上定义自定义方法以扩展其功能。
type catalogAttributeTemplateDao struct {
	*internal.CatalogAttributeTemplateDao
}

var (
	// CatalogAttributeTemplate 为 catalog_attribute_template 表提供全局可用的 DAO 对象。
	CatalogAttributeTemplate = catalogAttributeTemplateDao{internal.NewCatalogAttributeTemplateDao()}
)

// 在此处扩展自定义方法和功能。
