// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/catalog-svc/internal/dao/internal"
)

// catalogIdempotencyDao 是 catalog_idempotency 表的 DAO。
// 可按需在其上定义自定义方法以扩展其功能。
type catalogIdempotencyDao struct {
	*internal.CatalogIdempotencyDao
}

var (
	// CatalogIdempotency 为 catalog_idempotency 表操作提供全局访问对象。
	CatalogIdempotency = catalogIdempotencyDao{internal.NewCatalogIdempotencyDao()}
)

// 在此处扩展自定义方法和功能。
