// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/catalog-svc/internal/dao/internal"
)

// catalogConsumerEventDedupDao 是 catalog_consumer_event_dedup 表的 DAO。
// 可按需在其上定义自定义方法以扩展其功能。
type catalogConsumerEventDedupDao struct {
	*internal.CatalogConsumerEventDedupDao
}

var (
	// CatalogConsumerEventDedup 为 catalog_consumer_event_dedup 表操作提供全局访问对象。
	CatalogConsumerEventDedup = catalogConsumerEventDedupDao{internal.NewCatalogConsumerEventDedupDao()}
)

// 在此处扩展自定义方法和功能。
