// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/catalog-svc/internal/dao/internal"
)

// catalogIdempotencyDao is the data access object for the table catalog_idempotency.
// You can define custom methods on it to extend its functionality as needed.
type catalogIdempotencyDao struct {
	*internal.CatalogIdempotencyDao
}

var (
	// CatalogIdempotency is a globally accessible object for table catalog_idempotency operations.
	CatalogIdempotency = catalogIdempotencyDao{internal.NewCatalogIdempotencyDao()}
)

// Add your custom methods and functionality below.
