// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/catalog-svc/internal/dao/internal"
)

// catalogSkuDao is the data access object for the table catalog_sku.
// You can define custom methods on it to extend its functionality as needed.
type catalogSkuDao struct {
	*internal.CatalogSkuDao
}

var (
	// CatalogSku is a globally accessible object for table catalog_sku operations.
	CatalogSku = catalogSkuDao{internal.NewCatalogSkuDao()}
)

// Add your custom methods and functionality below.
