// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/catalog-svc/internal/dao/internal"
)

// catalogBrandDao 是 catalog_brand 表的 DAO。
// 可按需在其上定义自定义方法以扩展其功能。
type catalogBrandDao struct {
	*internal.CatalogBrandDao
}

var (
	// CatalogBrand 为 catalog_brand 表操作提供全局可用的 DAO 对象。
	CatalogBrand = catalogBrandDao{internal.NewCatalogBrandDao()}
)

// 在此处扩展自定义方法和功能。
