// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/catalog-svc/internal/dao/internal"
)

// catalogCategoryDao 是 catalog_category 表的 DAO。
// 可按需在其上定义自定义方法以扩展其功能。
type catalogCategoryDao struct {
	*internal.CatalogCategoryDao
}

var (
	// CatalogCategory 为 catalog_category 表操作提供全局访问对象。
	CatalogCategory = catalogCategoryDao{internal.NewCatalogCategoryDao()}
)

// 在此处扩展自定义方法和功能。
