// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/catalog-svc/internal/dao/internal"
)

// catalogOutboxEventArchiveDao is the data access object for the table catalog_outbox_event_archive.
// You can define custom methods on it to extend its functionality as needed.
type catalogOutboxEventArchiveDao struct {
	*internal.CatalogOutboxEventArchiveDao
}

var (
	// CatalogOutboxEventArchive is a globally accessible object for table catalog_outbox_event_archive operations.
	CatalogOutboxEventArchive = catalogOutboxEventArchiveDao{internal.NewCatalogOutboxEventArchiveDao()}
)

// Add your custom methods and functionality below.
