// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/catalog-svc/internal/dao/internal"
)

// catalogReviewTaskDao is the data access object for the table catalog_review_task.
// You can define custom methods on it to extend its functionality as needed.
type catalogReviewTaskDao struct {
	*internal.CatalogReviewTaskDao
}

var (
	// CatalogReviewTask is a globally accessible object for table catalog_review_task operations.
	CatalogReviewTask = catalogReviewTaskDao{internal.NewCatalogReviewTaskDao()}
)

// Add your custom methods and functionality below.
