// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/catalog-svc/internal/dao/internal"
)

// catalogConsumerEventDedupDao is the data access object for the table catalog_consumer_event_dedup.
// You can define custom methods on it to extend its functionality as needed.
type catalogConsumerEventDedupDao struct {
	*internal.CatalogConsumerEventDedupDao
}

var (
	// CatalogConsumerEventDedup is a globally accessible object for table catalog_consumer_event_dedup operations.
	CatalogConsumerEventDedup = catalogConsumerEventDedupDao{internal.NewCatalogConsumerEventDedupDao()}
)

// Add your custom methods and functionality below.
