// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/catalog-svc/internal/dao/internal"
)

// catalogSpuDao 是 catalog_spu 表的数据访问对象。
// 可根据需要在其上添加自定义方法以扩展能力。
type catalogSpuDao struct {
	*internal.CatalogSpuDao
}

var (
	// CatalogSpu 为 catalog_spu 表操作提供全局可用的 DAO 对象。
	CatalogSpu = catalogSpuDao{internal.NewCatalogSpuDao()}
)

// 在下方添加自定义方法与扩展功能。
