// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/iam-svc/internal/dao/internal"
)

// iamUserOauthDao is the data access object for the table iam_user_oauth.
// You can define custom methods on it to extend its functionality as needed.
type iamUserOauthDao struct {
	*internal.IamUserOauthDao
}

var (
	// IamUserOauth is a globally accessible object for table iam_user_oauth operations.
	IamUserOauth = iamUserOauthDao{internal.NewIamUserOauthDao()}
)

// Add your custom methods and functionality below.
