// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/iam-svc/internal/dao/internal"
)

// iamUserRoleDao is the data access object for the table iam_user_role.
// You can define custom methods on it to extend its functionality as needed.
type iamUserRoleDao struct {
	*internal.IamUserRoleDao
}

var (
	// IamUserRole is a globally accessible object for table iam_user_role operations.
	IamUserRole = iamUserRoleDao{internal.NewIamUserRoleDao()}
)

// Add your custom methods and functionality below.
