// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/iam-svc/internal/dao/internal"
)

// iamOutboxEventArchiveDao is the data access object for the table iam_outbox_event_archive.
// You can define custom methods on it to extend its functionality as needed.
type iamOutboxEventArchiveDao struct {
	*internal.IamOutboxEventArchiveDao
}

var (
	// IamOutboxEventArchive is a globally accessible object for table iam_outbox_event_archive operations.
	IamOutboxEventArchive = iamOutboxEventArchiveDao{internal.NewIamOutboxEventArchiveDao()}
)

// Add your custom methods and functionality below.
