// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/iam-svc/internal/dao/internal"
)

// iamUserAuthDao is the data access object for the table iam_user_auth.
// You can define custom methods on it to extend its functionality as needed.
type iamUserAuthDao struct {
	*internal.IamUserAuthDao
}

var (
	// IamUserAuth is a globally accessible object for table iam_user_auth operations.
	IamUserAuth = iamUserAuthDao{internal.NewIamUserAuthDao()}
)

// Add your custom methods and functionality below.
