// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/iam-svc/internal/dao/internal"
)

// iamRefreshSessionDao is the data access object for the table iam_refresh_session.
// You can define custom methods on it to extend its functionality as needed.
type iamRefreshSessionDao struct {
	*internal.IamRefreshSessionDao
}

var (
	// IamRefreshSession is a globally accessible object for table iam_refresh_session operations.
	IamRefreshSession = iamRefreshSessionDao{internal.NewIamRefreshSessionDao()}
)

// Add your custom methods and functionality below.
