// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/iam-svc/internal/dao/internal"
)

// iamMembershipDao is the data access object for the table iam_membership.
// You can define custom methods on it to extend its functionality as needed.
type iamMembershipDao struct {
	*internal.IamMembershipDao
}

var (
	// IamMembership is a globally accessible object for table iam_membership operations.
	IamMembership = iamMembershipDao{internal.NewIamMembershipDao()}
)

// Add your custom methods and functionality below.
