// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/iam-svc/internal/dao/internal"
)

// iamSmsLogDao is the data access object for the table iam_sms_log.
// You can define custom methods on it to extend its functionality as needed.
type iamSmsLogDao struct {
	*internal.IamSmsLogDao
}

var (
	// IamSmsLog is a globally accessible object for table iam_sms_log operations.
	IamSmsLog = iamSmsLogDao{internal.NewIamSmsLogDao()}
)

// Add your custom methods and functionality below.
