// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/iam-svc/internal/dao/internal"
)

// iamOutboxEventDao is the data access object for the table iam_outbox_event.
// You can define custom methods on it to extend its functionality as needed.
type iamOutboxEventDao struct {
	*internal.IamOutboxEventDao
}

var (
	// IamOutboxEvent is a globally accessible object for table iam_outbox_event operations.
	IamOutboxEvent = iamOutboxEventDao{internal.NewIamOutboxEventDao()}
)

// Add your custom methods and functionality below.
