// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/iam-svc/internal/dao/internal"
)

// iamLoginLogDao is the data access object for the table iam_login_log.
// You can define custom methods on it to extend its functionality as needed.
type iamLoginLogDao struct {
	*internal.IamLoginLogDao
}

var (
	// IamLoginLog is a globally accessible object for table iam_login_log operations.
	IamLoginLog = iamLoginLogDao{internal.NewIamLoginLogDao()}
)

// Add your custom methods and functionality below.
