// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/promotion-svc/internal/dao/internal"
)

// couponTemplateDao is the data access object for the table coupon_template.
// You can define custom methods on it to extend its functionality as needed.
type couponTemplateDao struct {
	*internal.CouponTemplateDao
}

var (
	// CouponTemplate is a globally accessible object for table coupon_template operations.
	CouponTemplate = couponTemplateDao{internal.NewCouponTemplateDao()}
)

// Add your custom methods and functionality below.
