// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/promotion-svc/internal/dao/internal"
)

// couponLockDao is the data access object for the table coupon_lock.
// You can define custom methods on it to extend its functionality as needed.
type couponLockDao struct {
	*internal.CouponLockDao
}

var (
	// CouponLock is a globally accessible object for table coupon_lock operations.
	CouponLock = couponLockDao{internal.NewCouponLockDao()}
)

// Add your custom methods and functionality below.
