// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/promotion-svc/internal/dao/internal"
)

// couponUserDao is the data access object for the table coupon_user.
// You can define custom methods on it to extend its functionality as needed.
type couponUserDao struct {
	*internal.CouponUserDao
}

var (
	// CouponUser is a globally accessible object for table coupon_user operations.
	CouponUser = couponUserDao{internal.NewCouponUserDao()}
)

// Add your custom methods and functionality below.
