// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/promotion-svc/internal/dao/internal"
)

// promotionCampaignDao is the data access object for the table promotion_campaign.
// You can define custom methods on it to extend its functionality as needed.
type promotionCampaignDao struct {
	*internal.PromotionCampaignDao
}

var (
	// PromotionCampaign is a globally accessible object for table promotion_campaign operations.
	PromotionCampaign = promotionCampaignDao{internal.NewPromotionCampaignDao()}
)

// Add your custom methods and functionality below.
