// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/promotion-svc/internal/dao/internal"
)

// promotionOutboxEventDao is the data access object for the table promotion_outbox_event.
// You can define custom methods on it to extend its functionality as needed.
type promotionOutboxEventDao struct {
	*internal.PromotionOutboxEventDao
}

var (
	// PromotionOutboxEvent is a globally accessible object for table promotion_outbox_event operations.
	PromotionOutboxEvent = promotionOutboxEventDao{internal.NewPromotionOutboxEventDao()}
)

// Add your custom methods and functionality below.
