// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/promotion-svc/internal/dao/internal"
)

// promotionRuleDao is the data access object for the table promotion_rule.
// You can define custom methods on it to extend its functionality as needed.
type promotionRuleDao struct {
	*internal.PromotionRuleDao
}

var (
	// PromotionRule is a globally accessible object for table promotion_rule operations.
	PromotionRule = promotionRuleDao{internal.NewPromotionRuleDao()}
)

// Add your custom methods and functionality below.
