USE `shopa_edge_gateway`;
SET NAMES utf8mb4;

-- 修复 edge_proxy_route 列注释
ALTER TABLE `edge_proxy_route`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  MODIFY COLUMN `route_code` VARCHAR(64) NOT NULL COMMENT '路由编码（全局唯一）',
  MODIFY COLUMN `method` VARCHAR(16) NOT NULL COMMENT 'HTTP方法',
  MODIFY COLUMN `path_pattern` VARCHAR(255) NOT NULL COMMENT '网关路由匹配路径',
  MODIFY COLUMN `upstream_service` VARCHAR(64) NOT NULL COMMENT '目标上游服务标识',
  MODIFY COLUMN `upstream_path_template` VARCHAR(255) NOT NULL COMMENT '目标上游路径模板',
  MODIFY COLUMN `auth_required` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否需要鉴权',
  MODIFY COLUMN `inject_user_context` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否注入用户上下文头',
  MODIFY COLUMN `body_mode` ENUM('STREAM','NORMAL') NOT NULL DEFAULT 'NORMAL' COMMENT '请求体处理模式',
  MODIFY COLUMN `timeout_ms` INT UNSIGNED NOT NULL DEFAULT 15000 COMMENT '上游调用超时时间（毫秒）',
  MODIFY COLUMN `rate_limit_rps` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '每秒限流阈值，0表示不限流',
  MODIFY COLUMN `status` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '状态：1启用 0停用',
  MODIFY COLUMN `remark` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '备注',
  MODIFY COLUMN `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  MODIFY COLUMN `deleted_at` DATETIME NULL DEFAULT NULL COMMENT '软删除时间';

ALTER TABLE `edge_proxy_route` COMMENT = '网关透传路由策略表';

-- 修复 edge_request_audit 列注释
ALTER TABLE `edge_request_audit`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  MODIFY COLUMN `request_id` VARCHAR(64) NOT NULL COMMENT '请求ID（全局唯一）',
  MODIFY COLUMN `route_code` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '命中路由编码',
  MODIFY COLUMN `user_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '调用用户ID',
  MODIFY COLUMN `method` VARCHAR(16) NOT NULL COMMENT 'HTTP方法',
  MODIFY COLUMN `path` VARCHAR(255) NOT NULL COMMENT '请求路径',
  MODIFY COLUMN `upstream_service` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '上游服务标识',
  MODIFY COLUMN `status_code` INT NOT NULL DEFAULT 0 COMMENT 'HTTP状态码',
  MODIFY COLUMN `latency_ms` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '请求耗时毫秒',
  MODIFY COLUMN `partial` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否降级返回',
  MODIFY COLUMN `degraded_fields_json` JSON NULL COMMENT '降级字段列表',
  MODIFY COLUMN `error_code` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '业务错误码',
  MODIFY COLUMN `client_ip` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '客户端IP',
  MODIFY COLUMN `user_agent` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '客户端UA',
  MODIFY COLUMN `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE `edge_request_audit` COMMENT = '网关请求审计表';

-- 修复初始化路由备注
UPDATE `edge_proxy_route` SET `remark` = '商家创建商品草稿' WHERE `route_code` = 'EGW_CATALOG_CREATE_DRAFT';
UPDATE `edge_proxy_route` SET `remark` = '商家批量更新SKU草稿' WHERE `route_code` = 'EGW_CATALOG_UPSERT_SKU';
UPDATE `edge_proxy_route` SET `remark` = '媒体上传流式透传' WHERE `route_code` = 'EGW_MEDIA_UPLOAD';
