// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/aftersale-svc/internal/dao/internal"
)

// aftersaleOutboxEventDao is the data access object for the table aftersale_outbox_event.
// You can define custom methods on it to extend its functionality as needed.
type aftersaleOutboxEventDao struct {
	*internal.AftersaleOutboxEventDao
}

var (
	// AftersaleOutboxEvent is a globally accessible object for table aftersale_outbox_event operations.
	AftersaleOutboxEvent = aftersaleOutboxEventDao{internal.NewAftersaleOutboxEventDao()}
)

// Add your custom methods and functionality below.
