// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/aftersale-svc/internal/dao/internal"
)

// aftersaleOperateLogDao is the data access object for the table aftersale_operate_log.
// You can define custom methods on it to extend its functionality as needed.
type aftersaleOperateLogDao struct {
	*internal.AftersaleOperateLogDao
}

var (
	// AftersaleOperateLog is a globally accessible object for table aftersale_operate_log operations.
	AftersaleOperateLog = aftersaleOperateLogDao{internal.NewAftersaleOperateLogDao()}
)

// Add your custom methods and functionality below.
