// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/aftersale-svc/internal/dao/internal"
)

// afterSaleCaseDao is the data access object for the table after_sale_case.
// You can define custom methods on it to extend its functionality as needed.
type afterSaleCaseDao struct {
	*internal.AfterSaleCaseDao
}

var (
	// AfterSaleCase is a globally accessible object for table after_sale_case operations.
	AfterSaleCase = afterSaleCaseDao{internal.NewAfterSaleCaseDao()}
)

// Add your custom methods and functionality below.
