// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/aftersale-svc/internal/dao/internal"
)

// aftersaleIdempotencyDao is the data access object for the table aftersale_idempotency.
// You can define custom methods on it to extend its functionality as needed.
type aftersaleIdempotencyDao struct {
	*internal.AftersaleIdempotencyDao
}

var (
	// AftersaleIdempotency is a globally accessible object for table aftersale_idempotency operations.
	AftersaleIdempotency = aftersaleIdempotencyDao{internal.NewAftersaleIdempotencyDao()}
)

// Add your custom methods and functionality below.
