// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/inventory-svc/internal/dao/internal"
)

// inventoryOutboxEventArchiveDao is the data access object for the table inventory_outbox_event_archive.
// You can define custom methods on it to extend its functionality as needed.
type inventoryOutboxEventArchiveDao struct {
	*internal.InventoryOutboxEventArchiveDao
}

var (
	// InventoryOutboxEventArchive is a globally accessible object for table inventory_outbox_event_archive operations.
	InventoryOutboxEventArchive = inventoryOutboxEventArchiveDao{internal.NewInventoryOutboxEventArchiveDao()}
)

// Add your custom methods and functionality below.
