// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/inventory-svc/internal/dao/internal"
)

// inventoryReservationItemDao 是 inventory_reservation_item 表的数据访问对象。
// 可在此基础上定义自定义方法以扩展功能。
type inventoryReservationItemDao struct {
	*internal.InventoryReservationItemDao
}

var (
	// InventoryReservationItem 是 inventory_reservation_item 表操作的全局可访问对象。
	InventoryReservationItem = inventoryReservationItemDao{internal.NewInventoryReservationItemDao()}
)

// 在下方添加自定义方法与逻辑。
