// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/inventory-svc/internal/dao/internal"
)

// inventoryOutboxEventDao is the data access object for the table inventory_outbox_event.
// You can define custom methods on it to extend its functionality as needed.
type inventoryOutboxEventDao struct {
	*internal.InventoryOutboxEventDao
}

var (
	// InventoryOutboxEvent is a globally accessible object for table inventory_outbox_event operations.
	InventoryOutboxEvent = inventoryOutboxEventDao{internal.NewInventoryOutboxEventDao()}
)

// Add your custom methods and functionality below.
