// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/inventory-svc/internal/dao/internal"
)

// inventoryConsumerEventDedupDao is the data access object for the table inventory_consumer_event_dedup.
// You can define custom methods on it to extend its functionality as needed.
type inventoryConsumerEventDedupDao struct {
	*internal.InventoryConsumerEventDedupDao
}

var (
	// InventoryConsumerEventDedup is a globally accessible object for table inventory_consumer_event_dedup operations.
	InventoryConsumerEventDedup = inventoryConsumerEventDedupDao{internal.NewInventoryConsumerEventDedupDao()}
)

// Add your custom methods and functionality below.
