// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/inventory-svc/internal/dao/internal"
)

// inventoryOutboxEventArchiveDao 是 inventory_outbox_event_archive 表的数据访问对象。
// 可在此基础上定义自定义方法以扩展功能。
type inventoryOutboxEventArchiveDao struct {
	*internal.InventoryOutboxEventArchiveDao
}

var (
	// InventoryOutboxEventArchive 是 inventory_outbox_event_archive 表操作的全局可访问对象。
	InventoryOutboxEventArchive = inventoryOutboxEventArchiveDao{internal.NewInventoryOutboxEventArchiveDao()}
)

// 在下方添加自定义方法与逻辑。
