// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/inventory-svc/internal/dao/internal"
)

// inventoryReservationDao is the data access object for the table inventory_reservation.
// You can define custom methods on it to extend its functionality as needed.
type inventoryReservationDao struct {
	*internal.InventoryReservationDao
}

var (
	// InventoryReservation is a globally accessible object for table inventory_reservation operations.
	InventoryReservation = inventoryReservationDao{internal.NewInventoryReservationDao()}
)

// Add your custom methods and functionality below.
