// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/inventory-svc/internal/dao/internal"
)

// inventoryConsumerEventDedupDao 是 inventory_consumer_event_dedup 表的 数据访问对象。
// 可在此基础上定义自定义方法以扩展功能。
type inventoryConsumerEventDedupDao struct {
	*internal.InventoryConsumerEventDedupDao
}

var (
	// InventoryConsumerEventDedup 是 inventory_consumer_event_dedup 表操作的全局可访问对象。
	InventoryConsumerEventDedup = inventoryConsumerEventDedupDao{internal.NewInventoryConsumerEventDedupDao()}
)

// 在下方添加自定义方法与逻辑。
