// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/inventory-svc/internal/dao/internal"
)

// inventorySkuContextDao 是 inventory_sku_context 表的数据访问对象。
// 可在此基础上定义自定义方法以扩展功能。
type inventorySkuContextDao struct {
	*internal.InventorySkuContextDao
}

var (
	// InventorySkuContext 是 inventory_sku_context 表操作的全局可访问对象。
	InventorySkuContext = inventorySkuContextDao{internal.NewInventorySkuContextDao()}
)

// 在下方添加自定义方法与逻辑。
