// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/inventory-svc/internal/dao/internal"
)

// inventoryLedgerDao 是 inventory_ledger 表的数据访问对象。
// 可在此基础上定义自定义方法以扩展功能。
type inventoryLedgerDao struct {
	*internal.InventoryLedgerDao
}

var (
	// InventoryLedger 是 inventory_ledger 表操作的全局可访问对象。
	InventoryLedger = inventoryLedgerDao{internal.NewInventoryLedgerDao()}
)

// 在下方添加自定义方法与逻辑。
