// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/inventory-svc/internal/dao/internal"
)

// inventorySkuContextDao is the data access object for the table inventory_sku_context.
// You can define custom methods on it to extend its functionality as needed.
type inventorySkuContextDao struct {
	*internal.InventorySkuContextDao
}

var (
	// InventorySkuContext is a globally accessible object for table inventory_sku_context operations.
	InventorySkuContext = inventorySkuContextDao{internal.NewInventorySkuContextDao()}
)

// Add your custom methods and functionality below.
