// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/inventory-svc/internal/dao/internal"
)

// inventoryIdempotencyDao is the data access object for the table inventory_idempotency.
// You can define custom methods on it to extend its functionality as needed.
type inventoryIdempotencyDao struct {
	*internal.InventoryIdempotencyDao
}

var (
	// InventoryIdempotency is a globally accessible object for table inventory_idempotency operations.
	InventoryIdempotency = inventoryIdempotencyDao{internal.NewInventoryIdempotencyDao()}
)

// Add your custom methods and functionality below.
