// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/inventory-svc/internal/dao/internal"
)

// inventoryIdempotencyDao 是 inventory_idempotency 表的数据访问对象。
// 可在此基础上定义自定义方法以扩展功能。
type inventoryIdempotencyDao struct {
	*internal.InventoryIdempotencyDao
}

var (
	// InventoryIdempotency 是 inventory_idempotency 表操作的全局可访问对象。
	InventoryIdempotency = inventoryIdempotencyDao{internal.NewInventoryIdempotencyDao()}
)

// 在下方添加自定义方法与逻辑。
