// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/inventory-svc/internal/dao/internal"
)

// inventoryReservationItemDao is the data access object for the table inventory_reservation_item.
// You can define custom methods on it to extend its functionality as needed.
type inventoryReservationItemDao struct {
	*internal.InventoryReservationItemDao
}

var (
	// InventoryReservationItem is a globally accessible object for table inventory_reservation_item operations.
	InventoryReservationItem = inventoryReservationItemDao{internal.NewInventoryReservationItemDao()}
)

// Add your custom methods and functionality below.
