// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/inventory-svc/internal/dao/internal"
)

// inventoryStockDao is the data access object for the table inventory_stock.
// You can define custom methods on it to extend its functionality as needed.
type inventoryStockDao struct {
	*internal.InventoryStockDao
}

var (
	// InventoryStock is a globally accessible object for table inventory_stock operations.
	InventoryStock = inventoryStockDao{internal.NewInventoryStockDao()}
)

// Add your custom methods and functionality below.
