// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/notification-svc/internal/dao/internal"
)

// notificationDeadLetterDao is the data access object for the table notification_dead_letter.
// You can define custom methods on it to extend its functionality as needed.
type notificationDeadLetterDao struct {
	*internal.NotificationDeadLetterDao
}

var (
	// NotificationDeadLetter is a globally accessible object for table notification_dead_letter operations.
	NotificationDeadLetter = notificationDeadLetterDao{internal.NewNotificationDeadLetterDao()}
)

// Add your custom methods and functionality below.
