// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/notification-svc/internal/dao/internal"
)

// notificationTemplateDao is the data access object for the table notification_template.
// You can define custom methods on it to extend its functionality as needed.
type notificationTemplateDao struct {
	*internal.NotificationTemplateDao
}

var (
	// NotificationTemplate is a globally accessible object for table notification_template operations.
	NotificationTemplate = notificationTemplateDao{internal.NewNotificationTemplateDao()}
)

// Add your custom methods and functionality below.
