// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/notification-svc/internal/dao/internal"
)

// notificationOutboxEventDao is the data access object for the table notification_outbox_event.
// You can define custom methods on it to extend its functionality as needed.
type notificationOutboxEventDao struct {
	*internal.NotificationOutboxEventDao
}

var (
	// NotificationOutboxEvent is a globally accessible object for table notification_outbox_event operations.
	NotificationOutboxEvent = notificationOutboxEventDao{internal.NewNotificationOutboxEventDao()}
)

// Add your custom methods and functionality below.
