// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/notification-svc/internal/dao/internal"
)

// notificationChannelRecordDao is the data access object for the table notification_channel_record.
// You can define custom methods on it to extend its functionality as needed.
type notificationChannelRecordDao struct {
	*internal.NotificationChannelRecordDao
}

var (
	// NotificationChannelRecord is a globally accessible object for table notification_channel_record operations.
	NotificationChannelRecord = notificationChannelRecordDao{internal.NewNotificationChannelRecordDao()}
)

// Add your custom methods and functionality below.
