// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/notification-svc/internal/dao/internal"
)

// notificationTaskDao is the data access object for the table notification_task.
// You can define custom methods on it to extend its functionality as needed.
type notificationTaskDao struct {
	*internal.NotificationTaskDao
}

var (
	// NotificationTask is a globally accessible object for table notification_task operations.
	NotificationTask = notificationTaskDao{internal.NewNotificationTaskDao()}
)

// Add your custom methods and functionality below.
