// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/notification-svc/internal/dao/internal"
)

// userNotificationPreferenceDao is the data access object for the table user_notification_preference.
// You can define custom methods on it to extend its functionality as needed.
type userNotificationPreferenceDao struct {
	*internal.UserNotificationPreferenceDao
}

var (
	// UserNotificationPreference is a globally accessible object for table user_notification_preference operations.
	UserNotificationPreference = userNotificationPreferenceDao{internal.NewUserNotificationPreferenceDao()}
)

// Add your custom methods and functionality below.
