CREATE TABLE IF NOT EXISTS search_spu_doc (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  spu_no VARCHAR(64) NOT NULL,
  shop_no VARCHAR(64) NOT NULL,
  shop_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  category_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  title VARCHAR(255) NOT NULL,
  sub_title VARCHAR(255) NOT NULL DEFAULT '',
  cover_image_asset_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  min_sale_price BIGINT UNSIGNED NOT NULL DEFAULT 0,
  max_sale_price BIGINT UNSIGNED NOT NULL DEFAULT 0,
  sold_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
  shop_status_code VARCHAR(32) NOT NULL DEFAULT '',
  on_shelf_status_code VARCHAR(32) NOT NULL DEFAULT '',
  tags_json TEXT,
  attr_tokens_json MEDIUMTEXT,
  searchable_text MEDIUMTEXT,
  source_version BIGINT UNSIGNED NOT NULL DEFAULT 0,
  source_updated_at DATETIME NULL,
  deleted TINYINT UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_spu_no (spu_no),
  KEY idx_keyword (title),
  KEY idx_shop_shelf (shop_no, on_shelf_status_code),
  KEY idx_category_price (category_id, min_sale_price)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS search_keyword_stat (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  keyword VARCHAR(191) NOT NULL,
  hit_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
  last_hit_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_keyword (keyword)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS search_rebuild_job (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  job_no VARCHAR(64) NOT NULL,
  status_code VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  trigger_by VARCHAR(64) NOT NULL DEFAULT '',
  reason_code VARCHAR(64) NOT NULL DEFAULT '',
  batch_size BIGINT UNSIGNED NOT NULL DEFAULT 0,
  total_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
  finished_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_job_no (job_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS search_outbox_event (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  event_no VARCHAR(64) NOT NULL,
  event_type VARCHAR(64) NOT NULL,
  payload_json MEDIUMTEXT,
  status TINYINT UNSIGNED NOT NULL DEFAULT 0,
  retry_count INT UNSIGNED NOT NULL DEFAULT 0,
  next_retry_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_event_no (event_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;