// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/risk-svc/internal/dao/internal"
)

// riskEventInboxDao is the data access object for the table risk_event_inbox.
// You can define custom methods on it to extend its functionality as needed.
type riskEventInboxDao struct {
	*internal.RiskEventInboxDao
}

var (
	// RiskEventInbox is a globally accessible object for table risk_event_inbox operations.
	RiskEventInbox = riskEventInboxDao{internal.NewRiskEventInboxDao()}
)

// Add your custom methods and functionality below.
