// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/risk-svc/internal/dao/internal"
)

// riskDecisionLogDao is the data access object for the table risk_decision_log.
// You can define custom methods on it to extend its functionality as needed.
type riskDecisionLogDao struct {
	*internal.RiskDecisionLogDao
}

var (
	// RiskDecisionLog is a globally accessible object for table risk_decision_log operations.
	RiskDecisionLog = riskDecisionLogDao{internal.NewRiskDecisionLogDao()}
)

// Add your custom methods and functionality below.
