// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/risk-svc/internal/dao/internal"
)

// riskRuleVersionDao is the data access object for the table risk_rule_version.
// You can define custom methods on it to extend its functionality as needed.
type riskRuleVersionDao struct {
	*internal.RiskRuleVersionDao
}

var (
	// RiskRuleVersion is a globally accessible object for table risk_rule_version operations.
	RiskRuleVersion = riskRuleVersionDao{internal.NewRiskRuleVersionDao()}
)

// Add your custom methods and functionality below.
