// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/risk-svc/internal/dao/internal"
)

// riskHitLogDao is the data access object for the table risk_hit_log.
// You can define custom methods on it to extend its functionality as needed.
type riskHitLogDao struct {
	*internal.RiskHitLogDao
}

var (
	// RiskHitLog is a globally accessible object for table risk_hit_log operations.
	RiskHitLog = riskHitLogDao{internal.NewRiskHitLogDao()}
)

// Add your custom methods and functionality below.
