// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/risk-svc/internal/dao/internal"
)

// riskFeatureSnapshotDao is the data access object for the table risk_feature_snapshot.
// You can define custom methods on it to extend its functionality as needed.
type riskFeatureSnapshotDao struct {
	*internal.RiskFeatureSnapshotDao
}

var (
	// RiskFeatureSnapshot is a globally accessible object for table risk_feature_snapshot operations.
	RiskFeatureSnapshot = riskFeatureSnapshotDao{internal.NewRiskFeatureSnapshotDao()}
)

// Add your custom methods and functionality below.
