// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/risk-svc/internal/dao/internal"
)

// riskWhitelistDao is the data access object for the table risk_whitelist.
// You can define custom methods on it to extend its functionality as needed.
type riskWhitelistDao struct {
	*internal.RiskWhitelistDao
}

var (
	// RiskWhitelist is a globally accessible object for table risk_whitelist operations.
	RiskWhitelist = riskWhitelistDao{internal.NewRiskWhitelistDao()}
)

// Add your custom methods and functionality below.
