CREATE TABLE IF NOT EXISTS promotion_campaign (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  campaign_no VARCHAR(64) NOT NULL,
  name VARCHAR(128) NOT NULL,
  status_code VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
  rule_json MEDIUMTEXT,
  start_at DATETIME NULL,
  end_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_campaign_no (campaign_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS promotion_rule (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  rule_code VARCHAR(64) NOT NULL,
  campaign_no VARCHAR(64) NOT NULL,
  rule_type VARCHAR(64) NOT NULL,
  condition_json MEDIUMTEXT,
  action_json MEDIUMTEXT,
  enabled TINYINT UNSIGNED NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_rule_code (rule_code),
  KEY idx_campaign_no (campaign_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS coupon_template (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  template_no VARCHAR(64) NOT NULL,
  campaign_no VARCHAR(64) NOT NULL,
  name VARCHAR(128) NOT NULL,
  threshold_amount BIGINT UNSIGNED NOT NULL DEFAULT 0,
  discount_amount BIGINT UNSIGNED NOT NULL DEFAULT 0,
  scope_json MEDIUMTEXT,
  stock_total BIGINT UNSIGNED NOT NULL DEFAULT 0,
  stock_used BIGINT UNSIGNED NOT NULL DEFAULT 0,
  status_code VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
  expire_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_template_no (template_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS coupon_user (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  coupon_no VARCHAR(64) NOT NULL,
  template_no VARCHAR(64) NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  status_code VARCHAR(32) NOT NULL DEFAULT 'UNUSED',
  lock_no VARCHAR(64) NOT NULL DEFAULT '',
  used_order_no VARCHAR(64) NOT NULL DEFAULT '',
  expire_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_coupon_no (coupon_no),
  KEY idx_user_status (user_id, status_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS coupon_lock (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  lock_no VARCHAR(64) NOT NULL,
  order_no VARCHAR(64) NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  coupon_nos_json TEXT,
  status_code VARCHAR(32) NOT NULL DEFAULT 'LOCKED',
  lock_expire_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_lock_no (lock_no),
  KEY idx_order_no (order_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS promotion_idempotency (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  idem_key VARCHAR(128) NOT NULL,
  biz_type VARCHAR(64) NOT NULL,
  biz_no VARCHAR(64) NOT NULL,
  response_json MEDIUMTEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_idem_biz (idem_key, biz_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS promotion_outbox_event (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  event_no VARCHAR(64) NOT NULL,
  event_type VARCHAR(64) NOT NULL,
  payload_json MEDIUMTEXT,
  status TINYINT UNSIGNED NOT NULL DEFAULT 0,
  retry_count INT UNSIGNED NOT NULL DEFAULT 0,
  next_retry_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_event_no (event_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;