// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/edge-gateway/internal/dao/internal"
)

// edgeRequestAuditDao is the data access object for the table edge_request_audit.
// You can define custom methods on it to extend its functionality as needed.
type edgeRequestAuditDao struct {
	*internal.EdgeRequestAuditDao
}

var (
	// EdgeRequestAudit is a globally accessible object for table edge_request_audit operations.
	EdgeRequestAudit = edgeRequestAuditDao{internal.NewEdgeRequestAuditDao()}
)

// Add your custom methods and functionality below.
