// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/edge-gateway/internal/dao/internal"
)

// edgeProxyRouteDao is the data access object for the table edge_proxy_route.
// You can define custom methods on it to extend its functionality as needed.
type edgeProxyRouteDao struct {
	*internal.EdgeProxyRouteDao
}

var (
	// EdgeProxyRoute is a globally accessible object for table edge_proxy_route operations.
	EdgeProxyRoute = edgeProxyRouteDao{internal.NewEdgeProxyRouteDao()}
)

// Add your custom methods and functionality below.
