// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/user-profile-svc/internal/dao/internal"
)

// consumerEventDedupDao is the data access object for the table consumer_event_dedup.
// You can define custom methods on it to extend its functionality as needed.
type consumerEventDedupDao struct {
	*internal.ConsumerEventDedupDao
}

var (
	// ConsumerEventDedup is a globally accessible object for table consumer_event_dedup operations.
	ConsumerEventDedup = consumerEventDedupDao{internal.NewConsumerEventDedupDao()}
)

// Add your custom methods and functionality below.
