// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/user-profile-svc/internal/dao/internal"
)

// consumerEventDedupDao 是 consumer_event_dedup 表的数据访问对象。
// 可在此结构上定义自定义方法以扩展能力。
type consumerEventDedupDao struct {
	*internal.ConsumerEventDedupDao
}

var (
	// ConsumerEventDedup 是用于 consumer_event_dedup 表操作的全局对象。
	ConsumerEventDedup = consumerEventDedupDao{internal.NewConsumerEventDedupDao()}
)

// 可在下方补充自定义方法与扩展行为。
