// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/user-profile-svc/internal/dao/internal"
)

// userProfileDao is the data access object for the table user_profile.
// You can define custom methods on it to extend its functionality as needed.
type userProfileDao struct {
	*internal.UserProfileDao
}

var (
	// UserProfile is a globally accessible object for table user_profile operations.
	UserProfile = userProfileDao{internal.NewUserProfileDao()}
)

// Add your custom methods and functionality below.
