// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/user-profile-svc/internal/dao/internal"
)

// userAddressDao 是 user_address 表的数据访问对象。
// 可以在此结构上添加自定义方法以扩展功能。
type userAddressDao struct {
	*internal.UserAddressDao
}

var (
	// UserAddress 是 user_address 表操作的全局访问对象。
	UserAddress = userAddressDao{internal.NewUserAddressDao()}
)

// 可在下方补充自定义方法与扩展逻辑。
