// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/user-profile-svc/internal/dao/internal"
)

// userProfileDao 是 user_profile 表的数据访问对象。
// 可以在此结构上定义自定义方法以扩展能力。
type userProfileDao struct {
	*internal.UserProfileDao
}

var (
	// UserProfile 是 user_profile 表操作的全局访问对象。
	UserProfile = userProfileDao{internal.NewUserProfileDao()}
)

// 可在下方补充自定义方法与扩展逻辑。
