CREATE TABLE IF NOT EXISTS `after_sale_case` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `after_sale_no` VARCHAR(64) NOT NULL,
  `order_no` VARCHAR(64) NOT NULL,
  `sub_order_no` VARCHAR(64) NOT NULL,
  `item_no` VARCHAR(64) NOT NULL,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `shop_no` VARCHAR(64) NOT NULL,
  `spu_no` VARCHAR(64) NOT NULL,
  `sku_no` VARCHAR(64) NOT NULL,
  `qty` INT UNSIGNED NOT NULL DEFAULT 1,
  `after_sale_type` TINYINT UNSIGNED NOT NULL,
  `after_sale_status` TINYINT UNSIGNED NOT NULL,
  `apply_refund_amount` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `approved_refund_amount` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `reason_code` VARCHAR(64) NOT NULL DEFAULT '',
  `reason_desc` VARCHAR(512) NOT NULL DEFAULT '',
  `evidence_asset_ids_json` JSON NULL,
  `buyer_remark` VARCHAR(512) NOT NULL DEFAULT '',
  `seller_reply` VARCHAR(512) NOT NULL DEFAULT '',
  `reject_reason_code` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `cancel_reason_code` VARCHAR(64) NOT NULL DEFAULT '',
  `version` BIGINT UNSIGNED NOT NULL DEFAULT 1,
  `closed_at` DATETIME(3) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted_at` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_after_sale_no` (`after_sale_no`),
  KEY `idx_user_status_created` (`user_id`,`after_sale_status`,`created_at`),
  KEY `idx_shop_status_created` (`shop_no`,`after_sale_status`,`created_at`),
  KEY `idx_sub_order_no` (`sub_order_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `refund_task` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `refund_task_no` VARCHAR(64) NOT NULL,
  `after_sale_no` VARCHAR(64) NOT NULL,
  `order_no` VARCHAR(64) NOT NULL,
  `sub_order_no` VARCHAR(64) NOT NULL,
  `pay_no` VARCHAR(64) NOT NULL DEFAULT '',
  `refund_amount` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `retry_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `next_retry_at` DATETIME(3) NULL,
  `last_error_code` VARCHAR(64) NOT NULL DEFAULT '',
  `last_error_message` VARCHAR(512) NOT NULL DEFAULT '',
  `version` BIGINT UNSIGNED NOT NULL DEFAULT 1,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted_at` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_refund_task_no` (`refund_task_no`),
  UNIQUE KEY `uk_after_sale_no` (`after_sale_no`),
  KEY `idx_status_next_retry` (`status`,`next_retry_at`),
  KEY `idx_order_no` (`order_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `aftersale_operate_log` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `after_sale_no` VARCHAR(64) NOT NULL,
  `operator_type` VARCHAR(32) NOT NULL,
  `operator_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `action_code` VARCHAR(64) NOT NULL,
  `from_status` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `to_status` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `reason_code` VARCHAR(64) NOT NULL DEFAULT '',
  `remark` VARCHAR(512) NOT NULL DEFAULT '',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_after_sale_created` (`after_sale_no`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `aftersale_outbox_event` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `event_id` VARCHAR(128) NOT NULL,
  `aggregate_type` VARCHAR(64) NOT NULL,
  `aggregate_no` VARCHAR(64) NOT NULL,
  `event_type` VARCHAR(64) NOT NULL,
  `payload_json` JSON NOT NULL,
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `available_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `sent_at` DATETIME(3) NULL,
  `retry_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `last_error` VARCHAR(255) NOT NULL DEFAULT '',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted_at` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_event_id` (`event_id`),
  KEY `idx_status_available` (`status`,`available_at`),
  KEY `idx_aggregate` (`aggregate_type`,`aggregate_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `aftersale_idempotency` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `idempotency_key` VARCHAR(128) NOT NULL,
  `action_code` VARCHAR(64) NOT NULL,
  `resource_no` VARCHAR(64) NOT NULL DEFAULT '',
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `response_json` JSON NULL,
  `error_code` VARCHAR(64) NOT NULL DEFAULT '',
  `expire_at` DATETIME(3) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_key_action` (`user_id`,`idempotency_key`,`action_code`),
  KEY `idx_resource_no` (`resource_no`),
  KEY `idx_expire_at` (`expire_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
