// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/cart-svc/internal/dao/internal"
)

// cartItemBackupDao is the data access object for the table cart_item_backup.
// You can define custom methods on it to extend its functionality as needed.
type cartItemBackupDao struct {
	*internal.CartItemBackupDao
}

var (
	// CartItemBackup is a globally accessible object for table cart_item_backup operations.
	CartItemBackup = cartItemBackupDao{internal.NewCartItemBackupDao()}
)

// Add your custom methods and functionality below.
