// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/cart-svc/internal/dao/internal"
)

// cartSyncCheckpointDao is the data access object for the table cart_sync_checkpoint.
// You can define custom methods on it to extend its functionality as needed.
type cartSyncCheckpointDao struct {
	*internal.CartSyncCheckpointDao
}

var (
	// CartSyncCheckpoint is a globally accessible object for table cart_sync_checkpoint operations.
	CartSyncCheckpoint = cartSyncCheckpointDao{internal.NewCartSyncCheckpointDao()}
)

// Add your custom methods and functionality below.
