// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/cart-svc/internal/dao/internal"
)

// cartOutboxEventDao is the data access object for the table cart_outbox_event.
// You can define custom methods on it to extend its functionality as needed.
type cartOutboxEventDao struct {
	*internal.CartOutboxEventDao
}

var (
	// CartOutboxEvent is a globally accessible object for table cart_outbox_event operations.
	CartOutboxEvent = cartOutboxEventDao{internal.NewCartOutboxEventDao()}
)

// Add your custom methods and functionality below.
