// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/chat-svc/internal/dao/internal"
)

// chatOutboxEventDao is the data access object for the table chat_outbox_event.
// You can define custom methods on it to extend its functionality as needed.
type chatOutboxEventDao struct {
	*internal.ChatOutboxEventDao
}

var (
	// ChatOutboxEvent is a globally accessible object for table chat_outbox_event operations.
	ChatOutboxEvent = chatOutboxEventDao{internal.NewChatOutboxEventDao()}
)

// Add your custom methods and functionality below.
