// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/chat-svc/internal/dao/internal"
)

// chatReadOffsetDao is the data access object for the table chat_read_offset.
// You can define custom methods on it to extend its functionality as needed.
type chatReadOffsetDao struct {
	*internal.ChatReadOffsetDao
}

var (
	// ChatReadOffset is a globally accessible object for table chat_read_offset operations.
	ChatReadOffset = chatReadOffsetDao{internal.NewChatReadOffsetDao()}
)

// Add your custom methods and functionality below.
