// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/chat-svc/internal/dao/internal"
)

// chatMessageDao is the data access object for the table chat_message.
// You can define custom methods on it to extend its functionality as needed.
type chatMessageDao struct {
	*internal.ChatMessageDao
}

var (
	// ChatMessage is a globally accessible object for table chat_message operations.
	ChatMessage = chatMessageDao{internal.NewChatMessageDao()}
)

// Add your custom methods and functionality below.
