// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/chat-svc/internal/dao/internal"
)

// chatIdempotencyDao is the data access object for the table chat_idempotency.
// You can define custom methods on it to extend its functionality as needed.
type chatIdempotencyDao struct {
	*internal.ChatIdempotencyDao
}

var (
	// ChatIdempotency is a globally accessible object for table chat_idempotency operations.
	ChatIdempotency = chatIdempotencyDao{internal.NewChatIdempotencyDao()}
)

// Add your custom methods and functionality below.
