// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/review-svc/internal/dao/internal"
)

// reviewIdempotencyDao is the data access object for the table review_idempotency.
// You can define custom methods on it to extend its functionality as needed.
type reviewIdempotencyDao struct {
	*internal.ReviewIdempotencyDao
}

var (
	// ReviewIdempotency is a globally accessible object for table review_idempotency operations.
	ReviewIdempotency = reviewIdempotencyDao{internal.NewReviewIdempotencyDao()}
)

// Add your custom methods and functionality below.
