// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/review-svc/internal/dao/internal"
)

// reviewOutboxEventDao is the data access object for the table review_outbox_event.
// You can define custom methods on it to extend its functionality as needed.
type reviewOutboxEventDao struct {
	*internal.ReviewOutboxEventDao
}

var (
	// ReviewOutboxEvent is a globally accessible object for table review_outbox_event operations.
	ReviewOutboxEvent = reviewOutboxEventDao{internal.NewReviewOutboxEventDao()}
)

// Add your custom methods and functionality below.
