// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/review-svc/internal/dao/internal"
)

// reviewRecordDao is the data access object for the table review_record.
// You can define custom methods on it to extend its functionality as needed.
type reviewRecordDao struct {
	*internal.ReviewRecordDao
}

var (
	// ReviewRecord is a globally accessible object for table review_record operations.
	ReviewRecord = reviewRecordDao{internal.NewReviewRecordDao()}
)

// Add your custom methods and functionality below.
