// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/review-svc/internal/dao/internal"
)

// reviewSpuSummaryDao is the data access object for the table review_spu_summary.
// You can define custom methods on it to extend its functionality as needed.
type reviewSpuSummaryDao struct {
	*internal.ReviewSpuSummaryDao
}

var (
	// ReviewSpuSummary is a globally accessible object for table review_spu_summary operations.
	ReviewSpuSummary = reviewSpuSummaryDao{internal.NewReviewSpuSummaryDao()}
)

// Add your custom methods and functionality below.
