// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/review-svc/internal/dao/internal"
)

// reviewOperateLogDao is the data access object for the table review_operate_log.
// You can define custom methods on it to extend its functionality as needed.
type reviewOperateLogDao struct {
	*internal.ReviewOperateLogDao
}

var (
	// ReviewOperateLog is a globally accessible object for table review_operate_log operations.
	ReviewOperateLog = reviewOperateLogDao{internal.NewReviewOperateLogDao()}
)

// Add your custom methods and functionality below.
