// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/search-svc/internal/dao/internal"
)

// searchOutboxEventDao is the data access object for the table search_outbox_event.
// You can define custom methods on it to extend its functionality as needed.
type searchOutboxEventDao struct {
	*internal.SearchOutboxEventDao
}

var (
	// SearchOutboxEvent is a globally accessible object for table search_outbox_event operations.
	SearchOutboxEvent = searchOutboxEventDao{internal.NewSearchOutboxEventDao()}
)

// Add your custom methods and functionality below.
