// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/search-svc/internal/dao/internal"
)

// searchSpuDocDao is the data access object for the table search_spu_doc.
// You can define custom methods on it to extend its functionality as needed.
type searchSpuDocDao struct {
	*internal.SearchSpuDocDao
}

var (
	// SearchSpuDoc is a globally accessible object for table search_spu_doc operations.
	SearchSpuDoc = searchSpuDocDao{internal.NewSearchSpuDocDao()}
)

// Add your custom methods and functionality below.
