// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/search-svc/internal/dao/internal"
)

// searchRebuildJobDao is the data access object for the table search_rebuild_job.
// You can define custom methods on it to extend its functionality as needed.
type searchRebuildJobDao struct {
	*internal.SearchRebuildJobDao
}

var (
	// SearchRebuildJob is a globally accessible object for table search_rebuild_job operations.
	SearchRebuildJob = searchRebuildJobDao{internal.NewSearchRebuildJobDao()}
)

// Add your custom methods and functionality below.
