// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/search-svc/internal/dao/internal"
)

// searchKeywordStatDao is the data access object for the table search_keyword_stat.
// You can define custom methods on it to extend its functionality as needed.
type searchKeywordStatDao struct {
	*internal.SearchKeywordStatDao
}

var (
	// SearchKeywordStat is a globally accessible object for table search_keyword_stat operations.
	SearchKeywordStat = searchKeywordStatDao{internal.NewSearchKeywordStatDao()}
)

// Add your custom methods and functionality below.
