// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/payment-svc/internal/dao/internal"
)

// paymentIntentDao is the data access object for the table payment_intent.
// You can define custom methods on it to extend its functionality as needed.
type paymentIntentDao struct {
	*internal.PaymentIntentDao
}

var (
	// PaymentIntent is a globally accessible object for table payment_intent operations.
	PaymentIntent = paymentIntentDao{internal.NewPaymentIntentDao()}
)

// Add your custom methods and functionality below.
