// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/payment-svc/internal/dao/internal"
)

// paymentReconciliationRecordDao is the data access object for the table payment_reconciliation_record.
// You can define custom methods on it to extend its functionality as needed.
type paymentReconciliationRecordDao struct {
	*internal.PaymentReconciliationRecordDao
}

var (
	// PaymentReconciliationRecord is a globally accessible object for table payment_reconciliation_record operations.
	PaymentReconciliationRecord = paymentReconciliationRecordDao{internal.NewPaymentReconciliationRecordDao()}
)

// Add your custom methods and functionality below.
