// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/payment-svc/internal/dao/internal"
)

// paymentCallbackLogDao is the data access object for the table payment_callback_log.
// You can define custom methods on it to extend its functionality as needed.
type paymentCallbackLogDao struct {
	*internal.PaymentCallbackLogDao
}

var (
	// PaymentCallbackLog is a globally accessible object for table payment_callback_log operations.
	PaymentCallbackLog = paymentCallbackLogDao{internal.NewPaymentCallbackLogDao()}
)

// Add your custom methods and functionality below.
