// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/payment-svc/internal/dao/internal"
)

// paymentOutboxEventDao is the data access object for the table payment_outbox_event.
// You can define custom methods on it to extend its functionality as needed.
type paymentOutboxEventDao struct {
	*internal.PaymentOutboxEventDao
}

var (
	// PaymentOutboxEvent is a globally accessible object for table payment_outbox_event operations.
	PaymentOutboxEvent = paymentOutboxEventDao{internal.NewPaymentOutboxEventDao()}
)

// Add your custom methods and functionality below.
