// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/payment-svc/internal/dao/internal"
)

// paymentIdempotencyDao is the data access object for the table payment_idempotency.
// You can define custom methods on it to extend its functionality as needed.
type paymentIdempotencyDao struct {
	*internal.PaymentIdempotencyDao
}

var (
	// PaymentIdempotency is a globally accessible object for table payment_idempotency operations.
	PaymentIdempotency = paymentIdempotencyDao{internal.NewPaymentIdempotencyDao()}
)

// Add your custom methods and functionality below.
