// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/payment-svc/internal/dao/internal"
)

// paymentReconciliationTaskDao is the data access object for the table payment_reconciliation_task.
// You can define custom methods on it to extend its functionality as needed.
type paymentReconciliationTaskDao struct {
	*internal.PaymentReconciliationTaskDao
}

var (
	// PaymentReconciliationTask is a globally accessible object for table payment_reconciliation_task operations.
	PaymentReconciliationTask = paymentReconciliationTaskDao{internal.NewPaymentReconciliationTaskDao()}
)

// Add your custom methods and functionality below.
