// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/TsingpekTao/shopa/payment-svc/internal/dao/internal"
)

// refundTaskDao is the data access object for the table refund_task.
// You can define custom methods on it to extend its functionality as needed.
type refundTaskDao struct {
	*internal.RefundTaskDao
}

var (
	// RefundTask is a globally accessible object for table refund_task operations.
	RefundTask = refundTaskDao{internal.NewRefundTaskDao()}
)

// Add your custom methods and functionality below.
